### ISSUE TITLE
Beta 4.6.1 und Webinterface 1.1.0 bringt Fehlermeldung (API passt nicht)

### ISSUE THREAD

**Issue by sammie76-2** [einfall/serienrecorder#100]
Hallo,

ich habe gerade die aktuelle Beta von serienrecorder 4.6.1 und das aktuelle Webinterface 1.1.0 installiert. Ich erhalte dann aber die Fehlermeldung das das die API nicht passen würde (2.7 sei immer noch installiert).

**Comment by MacDisein** [comment]
Browsercache geleert?

**Comment by sammie76-2** [comment]
Ja. Passiert auch in einem anderen Browser, habe extra zwei getetestet und in beiden Fällen Browsercache vorher geleert.

**Comment by sammie76-2** [comment]
Ja, wurde neu gestartet. Im serienrecorder auf der Box und auch im Webinterface wird aber weiterhin 4.6.0 angezeigt. Lediglich ein Infofenster für die 4.6.1 wurde angezeigt. Ist das so korrekt?

Ich werde nochmal das serienrecorder Verzeichnis komplett löschen und beides (4.6.1 - also aktuelles ZIP von Github und das Webinterface 1.1.0) rüberkopieren. Dann Box nochmal starten, Bericht dann gleich nochmal.

**Comment by sammie76-2** [comment]
Komisch. Jetzt hat es gepasst. Beim ersten Mal habe ich eigentlich genau das gleiche gemacht. 

Sorry für die Umstände. Jetzt passt alles!
