### ISSUE TITLE
Exception friert Dreambox ein

### ISSUE THREAD

**Issue by pachi81** [einfall/serienrecorder#102]
Hi,
ich habe seit einiger Zeit das Problem, dass die komplette Dreambox ziemlich regelmäßig gegen 12:31 komplett einfriert. Im Display bleibt die Uhrzeit stehen und man hat nur noch über Telnet Zugriff, um sie neu zu starten.
Ich habe bei den letzten Auftreten mal ein log vor dem Reboot generiert und es scheint am Verarbeiten der TV-Planer e-mail zu liegen.
Daraufhin habe ich auf Version 4.6 aktualisiert, aber es passiert weiterhin.

Hier die Fehlermeldungen aus dem Log:
```
Mär 29 12:31:10 dm920 enigma2[289]: [SerienRecorder] Processing data from TV-Planer e-mail
Mär 29 12:31:10 dm920 enigma2[289]: Exception in thread Thread-132:
Mär 29 12:31:10 dm920 enigma2[289]: Traceback (most recent call last):
Mär 29 12:31:10 dm920 enigma2[289]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Mär 29 12:31:10 dm920 enigma2[289]:     self.run()
Mär 29 12:31:10 dm920 enigma2[289]:   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderCheckForRecording.py", line 60, in run
Mär 29 12:31:10 dm920 enigma2[289]:     self.process(data)
Mär 29 12:31:10 dm920 enigma2[289]:   File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorderCheckForRecording.py", line 70, in process
Mär 29 12:31:10 dm920 enigma2[289]:     for transmission in self.emailData[fsID]:
Mär 29 12:31:10 dm920 enigma2[289]: KeyError: '[name]'
```
[name] steht dabei für verschiedenen Serien. Insgesamt tritt die Exeception 4 mal in verschiedenen threads auf.
Kann dir die vollständigen Logs gerne per Mail senden!?

Vielen Dank!

MfG Michael

**Comment by MacDisein** [comment]
Es gibt im SerienRecorder in den Einstellungen unter „Logging“ die Option „Backup von TV-Planer E-Mail erstellen“ - kannst du die bitte aktivieren. Beim nächsten Timersuchlauf wird dann eine Datei erstellt. Die HTML Datei von der E-Mail bitte schicken.

**Comment by pachi81** [comment]
War schon aktiviert...
Wohin kann ich es senden?

**Comment by MacDisein** [comment]
Ich kann den Fehler mit der aktuellen Betaversion nicht nachvollziehen, du solltest aktualisieren.
Es gab am 30.12. noch einen Bugfix im Zusammenhang mit der TV-Planer E-Mail.

**Comment by MacDisein** [comment]
Die Betaversionen gibt es nicht als DEB, da musst du den Sourcecode herunterladen und auf der Box austauschen.

Hier die Anleitung:
http://einfall.github.io/serienrecorder/index.html#beta-version

**Comment by pachi81** [comment]
Hi,
habe heute die Beta "installiert" und die TV-Planer E-Mail wieder aktiviert (war im Urlaub und hatte es sicherheitshalber deaktiviert). Nun mal schauen, ob das Problem erneut auftritt.
Danke!

**Comment by pachi81** [comment]
Das Problem besteht weiterhin. 
Habe mir mal die Stelle angesehen: https://github.com/einfall/serienrecorder/blob/415ce17ef7922952e6db60cc94d3c587891066b9/src/SerienRecorderCheckForRecording.py#L70

Also wenn der title nicht in den E-Mail Daten enthalten ist, dann wird doch nie fsID auf key gesetzt und dann greift man aber mit der "unbekannten" fsID als key auf die emailData zu!? 
Aber eigentlich sollten sich ja nur Daten in JobQueue befinden, die auch in emailData vorhanden sind... Sehr komisch.
Aber die fsID für die es fehlschlägt, sind definitiv nicht in der Mail drin und sollten daher auch gar nicht in der jobQueue sein!?

Seltsam auch, dass die Logzeile:
`Apr 12 12:14:49 dm920 enigma2[16455]: [SerienRecorder] Processing data from TV-Planer e-mail`
erst nach den Exceptions kommt oder liegt das am logger?

(Habe den Quellcode aber auch nur mal grob überflogen...)

**Comment by MacDisein** [comment]
Also ich kann mir das gerade auch nicht erklären, in deinem aktuellen Debuglog ist ja zu erkennen, dass es jetzt zwar keinen Fehler mehr beim Parsen gibt, aber trotzdem 0 Ausstrahlungstermine in der E-Mail gefunden wurden.
Irgendwas gerät da durcheinander, ich frage mich nur, wieso du der Einzige mit dem Problem bist...

Könntest du bitte noch die TV-Planer E-Mail die zum Debuglog und das SerienRecorder Log auf dein OneDrive packen. Ich muss das jetzt mit der aktuellen Version noch mal nachstellen.

Im Moment ist allerdings eh der Wurm drin, weil Wunschliste aktuell keine Ausstrahlungstermine liefert und der SerienServer auch der Belastungsgrenze ist.

**Comment by pachi81** [comment]
Habs hochgeladen.
Mal ne Frage, wenn er nix in der Mail findet, geht er dann ohne Filter in getMarkers und holt dadurch alles? Dann würde es den Fehler erklären.

**Comment by MacDisein** [comment]
Die Mail die du bekommen hast, sieht seltsam aus, weil dort kein Startzeiten für die Sendungen enthalten sind, deswegen kann der SerienRecorder sie nicht korrekt verarbeiten.
Wie ich ja schon geschrieben hatte, gibt es im Moment einige Probleme bei Wunschliste - möglich, dass das auch teilweise die TV-Planer E-Mail betrifft.

Du kannst ja die kommende Tage mal gucken ob die Mail korrekte Inhalte enthält und dann auch verarbeitet wird.

**Comment by pachi81** [comment]
Ok, aktuell habe ich die Mailverarbeitung deaktiviert, aber ich schaue mir die Mails mal an.
Es trat auch nicht jeden Tag auf.
Wäre schön, wenn es da vielleicht ne Fehlerbehandlung gibt, denn aktuell muss die Dreambox komplett neu gestartet werden, da sie nicht mehr reagiert und daher auch nix aufnimmt.
Aber ich kann es verstehen, wenn grad die Zeit knapp ist und es andere Baustellen gibt.

**Comment by pachi81** [comment]
Gerade nochmal geschaut, die Mail hat keine Startzeiten, da sie nur Stream Sendungen erhält.
Die müsste man ignorieren. Ich werde das mal deaktivieren, aber seit deren App nicht mehr funktioniert, muss man das über deren tolle Homepage machen...

**Comment by MacDisein** [comment]
Friert die Box denn auch mit der aktuellen Betaversion ein, ich kann mir das nicht vorstellen, das Log sah doch gut aus?!

**Comment by pachi81** [comment]
Ja, gestern hatte ich ja schon die aktuelle Beta drauf, als es passiert ist. Hatte extra geschaut und es hat 4.6.3-beta angezeigt.

**Comment by MacDisein** [comment]
Ich habe den Fehler gefunden, ich werde zeitnah eine neue Betaversion bereitstellen.
Vielen Dank für die umfangreichen Testdaten.

**Comment by pachi81** [comment]
Vielen Dank!!! Werde sie gleich einspielen.
