### ISSUE TITLE
Serienrecorder nicht synchron zu wunschliste.de?

### ISSUE THREAD

**Issue by chrisi51** [einfall/serienrecorder#103]
Aus welchen Gründen auch immer findet Serienrecorder auf meiner VU+ Uno4k keine Ausstrahltermine zu meinen Serienmarkern mehr. Wenn ich am PC aber auf Wunschliste.de schaue, sehe ich die ganzen Episoden, die ich nun verpasst habe bzw. verpassen werde =(

Hat sich vielleicht irgendwas auf wunschliste.de mit den Zugriffsrechten oder dem gelieferten Format geändert, so dass das nicht mehr korrekt geparst wird?

Habe es bei fast allen Serien ... bei den meisten gar keine Termine, bei einer nur noch die nächsten 2 Tage und bei einer komischerweise noch der gesamte Monat. 

Oder ist das eher ein lokales Problem in welcher Art auch immer?

**Comment by chrisi51** [comment]
PS: @MacDisein du hast DirectoryListening aktiv auf dem Webserver ... das  ist an sich schon nicht die idealeste Setting ... richtig schwierig wirds allerdings, wenns da ernsthaft was zu lesen gibt

**Comment by MacDisein** [comment]
@chrisi51: Danke für den Hinweis - habe ich abgestellt, sollte so natürlich nicht sein.

**Comment by chrisi51** [comment]
zurück zum eigentlichen problem:
habe gerade festgestellt, dass das Problem offenbar Sendergebunden ist.

DMAX zB geht ganz normal ... nehme ich dort eine x-beliebige Sendung, findet Serienrecorder ausreichend lange Termine in der Zukunft.
Bei Nitro ist bei verschiedenen Sendungen jeweils Donnerstag Abend schluss ... 
Bei anderen Sendern wiederum findet er gar nichts .... bspw. Pro7

Also irgendwas muss da fehlinterpretiert werden.

**Comment by MacDisein** [comment]
Im Moment gibt es Probleme bei Wunschliste, die liefern für einige Serien bzw. Sender keine Ausstrahlungstermine.

**Comment by egn1** [comment]
Hallo,
    
    ich habe heute um 8:22 Uhr noch meine Mail für morgen bekommen.
    Sender: Anixe HD, sixx, BR, tagesschau24, ZDF, Das Erste
    
    On 13.04.2023 09:33, Christian
      Hillebrand wrote:
    
    
      
      nun scheints gar nicht mehr zu funktionieren also er
        bekommt für gar keinen sender mehr termine geliefert
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/einfall/serienrecorder/issues/103#issuecomment-1506489370",
"url": "https://github.com/einfall/serienrecorder/issues/103#issuecomment-1506489370",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chrisi51** [comment]
von mail sprechen wir hier ja nicht ;)

**Comment by MacDisein** [comment]
Wunschliste hat heute Mittag den Fehler beheben können und stellt wieder vollständige Daten zur Verfügung.
​Es kann aber nach wie vor zu Einschränkungen auf dem SerienServer kommen, weil der ja erstmal nach und nach die Daten zwischenspeichern muss.
