### ISSUE TITLE
Zusammengefasste Folgen lassen sich nicht manuell in die Timerliste eintragen

### ISSUE THREAD

**Issue by ts-schu** [einfall/serienrecorder#104]
Systeminformationen
Box-Typ: two
Image: 4.5.1r11-2021-10-29 / Experimental 2020-06-18
SerienRecorder Version: 4.6.5-beta
Datenbank Schema Version: 4.6.0
API Version: 2.9 / 2.9

Serie "Mord auf Shetland":
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/5a3a1e5b-8d69-488d-9055-6ce809bb8b77)
TimerDB:
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/7f55c578-8e68-4236-9644-0016aaaf2379)
Die Timer S05E03/04 und S05E05/06 wurde automatisch angelegt, obwohl zuvor die Folgen S05 E01-06 manuell in die Timerliste eingefügt wurden.

Mein Vorschlag:

- Die Eingabemaske sollte ertüchtigt werden, dass auch solche zusammengefassten Episoden eingetragen werden können.

Andere Lösungen haben m.E. Nachteile für Leute, die schon die  Einzelepisoden haben, jedoch die Doppelepisoden noch aufnehmen wollen. SR scheint diese Doppelepisoden ja richtig zu behandeln (separat von den Einzelepisoden - siehe Liste der Timer), es fehlt jedoch die manuelle Eingabe.

**Comment by MacDisein** [comment]
Hast du davon zufällig noch das Logfile, also als die Timer für das Event angelegt wurden?
Und was hast du in den Einstellungen für "Event-Programmierungen behandeln" eingestellt?

**Comment by ts-schu** [comment]
Ich habe es an meiner Dreambox One reprodiziert:

Systeminformationen
Box-Typ: one
Image: 4.5.1r11-2021-10-29 / Experimental 2022-02-24
SerienRecorder Version: 4.6.5-beta
Datenbank Schema Version: 4.6.0
API Version: 2.9 / 2.9

Ich habe für Staffel 5 die Forgen 1-6 manuell eingetragen. Nach manuellem Timer-Suchlauf wurde die Folge S05E05/06 gefunden und aktiviert:
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/ff862d6d-6eb3-4d4e-b70a-caac0565474c)
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/9d824104-2a56-43ba-9f7e-ffd4f5331349)
Bzgl Event-Programmierungen:
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/38de1839-8808-4259-9199-6338f985e2cc)
Das sieht verdächtig nach einer Lösung für mein Problem aus :-)
Ich werde hier noch ein wenig runspielen.
Danke vorerst für Deine Hilfe.

**Comment by ts-schu** [comment]
Test ergab:
Diese Einstellung erzeugt das von mir gewünschte Verhalten:
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/6c65e01d-8ce2-4309-9b7a-53b404d8ce52)
Es wurde nach Löschen des Timers und neuem manuellen Timer-Suchlauf kein neuer Timer erzeugt.
Die Einzelepisoden wurden wie beschrieben angelegt:
![grafik](https://github.com/einfall/serienrecorder/assets/109224314/da2a4c2e-313f-451f-b739-2919e3b185b4)
(Anmerkung: die vorhandenen, manuellen Einträge könnten m.E. durch die neuen ersetzt werden -> nur optische Unschönheit :-) )

"Episoden-Titel beim Vergleich berücksichtigen"==True: funktioniert in meinem Fall nicht, da scheinbar der Text "manuell ..." dem Vergleich in die Quere kommt.

Vielen Dank für Deine Hilfe, für mich ist das Problem gelöst.

BTW: ich habe ein weiteres Problem bzgl der Serie "Elefant, Tiger & Co", das **NICHT** auf SerienRecorder zurückzuführen ist. Hier werden keine Episodennummern eingetragen. Der Grund ist: www.wunschliste.de hat keine Episodennummern hinterlegt (nur sporadisch erscheint mal eine). Die assoziierte Seite "www.fernsehserien.de" hat jedoch Episodennummern.
Leider reagiert Wunschliste nicht auf meine Fehlermeldung über "https://www.wunschliste.de/kontakt" . Hast Du da bessere Beziehungen?
