### ISSUE TITLE
Fehlerhafte Seriennummerierung

### ISSUE THREAD

**Issue by ZurigoX** [einfall/serienrecorder#105]
Bei der Serie The Oaht, heissen die Folgen S01E05 und S02E01 in Deutsch gleich (Rache).
Nun hat der Serienrcorder die Folge S01E05 unter der S02E01 als Teimer erstellt. 
Der Sendtermin ist der 06.01.2024 03:00-03:45 Uhr auf AXN Black.

Daruaf gekommen bin ich, da er mir die S01E05 nie in den Timern Angezeigt hat. Nach einiger Zeit ist mir der Identische Folgenname aufgefallen. Bei der überprüfung der Beschreibung habe ich den Fehler festgestellt.

Der Fall wird wohl nur sehr selten auftreten und somit nicht so wichtig sein.

**Comment by MacDisein** [comment]
Da der SerienRecorder seine Daten von Wunschliste.de bezieht, kann ich da wenig machen, das haben die scheinbar verwechselt. Am besten du schreibst an Wunschliste und bittest darum den Fehler zu korrigieren.

**Comment by ZurigoX** [comment]
Super. Besten Dank. Das war mir nicht aufgefallen.
Sorry für die Störung.
Mail an Wunschliste ist gemacht.
