### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by betonme** [einfall/serienrecorder#35]
I have started to implement the API for the Web Interface, see Pull Request 34
https://github.com/einfall/serienrecorder/pull/34

But actually I've not the time to complete it.

Next steps:
Define and Implement API functions:
- Get settopbox channels - Done
- Get channels from Wunschliste - Done
- Search a specific serie by name at Wunschliste - Done
- Search all events by series id - Done
  Further?
- Save channel match
- Get series list from user

Implement the User Web Interface.

**Comment by cedi84** [comment]
cool

**Comment by cedi84** [comment]
gehts hier noch weiter?

**Comment by Lynsch** [comment]
Same question here

**Comment by betonme** [comment]
Yes, would be nice. But no free time to implement it.

**Comment by unbeatable2** [comment]
@betonme 

Can you please make a detailed list of things which have still to be implemented (a list with deep details for a professional programmer)?
Unfortunately I am not good at programming, but we can announce the "web interface project" on a platform like http://www.freelancermap.de/projektboerse/programmierung-1
Therefore everyone can contribute to the serienrecorder plugin with a (small) donation.

Anyone interested in my suggestion? If so, we should collect donations on a paypal account and then announce the project on an external platform like mentioned before.

**Comment by unbeatable2** [comment]
Since nobody seems to be interested in the completion of the web interface, the issuce can be closed!

**Comment by cedi84** [comment]
hmmmm schade dass da niemand helfen kann :(

**Comment by jbleyel** [comment]
Wenn hier jemand in das Rest Interface alle notwendigen Funktionen einbaut, dann kann ich die UI in das Openwebif einbauen. !! NUR Openwebif !!

**Comment by jbleyel** [comment]
Die aktuelle Version funktioniert mal überhaupt nicht.
/serienrecorder

<img width="1222" alt="bildschirmfoto 2016-11-25 um 19 21 10" src="https://cloud.githubusercontent.com/assets/964927/20633219/5cfb138c-b344-11e6-8644-11c4d2986135.png">

**Comment by cedi84** [comment]
hi jbleyel

cool das sich da jemand rann macht.

denke es liegt an der umstellung von wunschliste, siehe hier:

https://www.vuplus-support.org/wbb4/index.php?thread/85765-serien-recorder-3-2-6-11-02-2016/&postID=1424259#post1424259

**Comment by MacDisein** [comment]
Ich schließe das Thema mal hier, inzwischen gibt es ein komplett neu entwickeltes Webinterface
