### ISSUE TITLE
Support andere Dateiformate für bereits bestehende Aufnahmen

### ISSUE THREAD

**Issue by gamebeast2k** [einfall/serienrecorder#43]
Hi,

wäre es möglich die Überprüfung ob eine Episode bereits aufgenommen wurde, nicht nur auf *.ts zubegrenzen ? Aus Speicherplatzgründen nutze ich das MKV Format. Was bei mehr als 4TB einfach mehr Sinn macht.
Spricht also etwas dagegen, die Suche auf einen Teil des Dateinames zubegrenzen ? 
Eine freie Formatwahl währe dann gegeben.

Danke im Vorraus

**Comment by MacDisein** [comment]
Der SerienRecorder speichert in seiner Datenbank welche Episoden aufgenommen wurden, das hat also nichts mit den Dateien auf der Festplatte zu tun. Der SerienRecorder merkt sich für welche Episoden er einen Timer angelegt hat, ob der Timer dann tatsächlich aufgenommen wurde oder ob die Aufnahme löschst, verschiebst, konvertierst oder umbenennt interessiert den SerienRecorder nicht mehr. Die Episode bleibt weiterhin als "bereits aufgenommen" markiert.

**Comment by andy71** [comment]
:+1

Ich stimme gamebeast2k zu. Es wäre sinnvoll auch andere Dateiformate zu bei der Suche zu erkennen.

MacDisein, Du liegst leider falsch. Der Serienrecorder sucht tatsächlich auch auf der Festplatte (im Serienverzeichnis) nach bereits vorhandenen Aufnahmen. Der Code dazu steht in der SerienRecorderHelpers.py.

Ich habe das für mich mal angepasst. Hier das Patchfile:

    --- SerienRecorderHelpers.py	2016-01-20 09:02:24.786721245 +0100
    +++ SerienRecorderHelpers.py_orig	2016-01-20 09:02:30.474721013 +0100
    @@ -323,9 +323,9 @@
     		count = 0
    		if fileExists(dirname):
     			if title is None:
    -				searchString = '%s.*?%s.*?\.(ts|mkv|avi|mp4|divx|xvid|mpg|mov)\Z' % (re.escape(serien_name), re.escape(seasonEpisodeString))
    +				searchString = '%s.*?%s.*?\.ts\Z' % (re.escape(serien_name), re.escape(seasonEpisodeString))
     			else:
    -				searchString = '%s.*?%s.*?%s.*?\.(ts|mkv|avi|mp4|divx|xvid|mpg|mov)\Z' % (re.escape(serien_name), re.escape(seasonEpisodeString), re.escape(title))
    +				searchString = '%s.*?%s.*?%s.*?\.ts\Z' % (re.escape(serien_name), re.escape(seasonEpisodeString), re.escape(title))
     			dirs = os.listdir(dirname)
     			for dir in dirs:
     				if re.search(searchString, dir):

Ich habe hier einfach mal die Dateierweiterungen ts, mkv, avi, mp4, divx, xvid, mpg und mov den regulären Ausdrücken hinzugefügt. Besser wäre vermutlich wenn diese über das SerienRecorder Setup einstellbar wären. Für meine Zwecke hat dies aber erstmal ausgereicht.

Falls jemand die SerienRecorderHelpers.py selbst anpassen möchte, bitte nicht vergessen danach die GUI neu zu starten :-)

Grüße
Andy

**Comment by MacDisein** [comment]
Hmmm, war mir gar nicht mehr bewusst - ich übernehme deinen Patch - wenn noch Bedarf nach weiteren Dateierweiterungen besteht kann ich ja immer noch eine GUI dafür bauen.

Danke!

**Comment by andy71** [comment]
Da nicht für ... wir haben zu Danken für Deinen stetigen Einsatz :-)
