### ISSUE TITLE
Serienrecorder wird bei FullHD Skins nicht korrekt angezeigt

### ISSUE THREAD

**Issue by stefan1983** [einfall/serienrecorder#44]
Hi,

ich verwende das myMetrix Skin als FullHD Variante (kann man in den Einstellungen einstellen), dabei wird der Serienrecorder falsch angezeigt (fest auf 720p skaliert??):

![img_0432](https://cloud.githubusercontent.com/assets/8542806/12533527/2e779228-c232-11e5-89ed-1e3715e84e66.JPG)

**Comment by MacDisein** [comment]
Dazu hatte ich schon etwas im VU+ Forum geschrieben.

**Comment by MacDisein** [comment]
Problem des Metrix Standard Skins im OpenATV Image.
Wurde von den Imagebauern behoben.
