### ISSUE TITLE
Timer wird ohne Sender erstellt

### ISSUE THREAD

**Issue by ch90045** [einfall/serienrecorder#45]
Seit neuestem werden Timer ohne Kanäle angelget - dem entsprechend klappen die Aufnahmen nicht.

**Comment by MacDisein** [comment]
Seit neuestem fährt mein Auto nicht mehr - dementsprechend kann ich nicht mehr fahren.
Etwas mehr Informationen machen Sinn - vielleicht kann man dir dann auch helfen!

Welche Kanäle betrifft das - oder generell alle?
Welche Version benutzt du?

**Comment by ch90045** [comment]
Guter Punkt - 3.2.5 und es betrifft alle Kanäle - ich habe die Zuordnung aller WebChannels zu den STBs noch mal geprüft und jedes noch einmal eingestellt (auch wenn sie richtig waren). Das ganze auf

openatv
VU+Duo2

Da ich von einer ET9200 zu dieser Box migriert habe (per DB import) setze ich das Ganze heute noch einmal "from scratch" auf - auch wenn es bis vor kurzem auch auf der neuen Box lief.

Was braucht ihr?

**Comment by MacDisein** [comment]
Der SerienRecorder legt ja enigma2 Timer an - dort wird dann die ServiceRef des Senders übergeben - wenn diese ServiceRef nicht stimmt - weil du die Datenbank übernommen hast, dann kann das schon sein. Bei der Kanalzuordnung reicht es nicht aus den selben Kanal noch einmal zu zuordnen, weil dann keine Änderung erkannt wird und deswegen nicht gespeichert wird.
Das werde ich mir bei Gelegenheit auch noch mal ansehen.
Es ist aber schon komisch, dass es bislang auf der neuen Box lief...

**Comment by Marti-Win7** [comment]
Das Problem mit dem fehlenden Sendern in den Timern hab ich ja auch. Im VU+ Forum hab ichs bei dem Problem mit der " Küstenwache " ja auch geschrieben und bei " TheBlacklist " hab ichs auch. Aber beides Pay-TV (Krimi, Crime )

**Comment by ch90045** [comment]
Aufsetzen von "scratch" hat es behoben ... trotzdem ... merkwürdig.
