### ISSUE TITLE
cover speicherort

### ISSUE THREAD

**Issue by cedi84** [einfall/serienrecorder#48]
hallo

also es ist ja möglich in den einstellungen den speicherort der cover anzugeben.
ich denke es macht sinn wen man als speicherort nicht ein pfad angeben kann sondern dass das cover im serien ordner erstellt wird.
somit würde bei jeder serie das cover abgespeichert.

mfg

**Comment by MacDisein** [comment]
Wenn du in den globalen Einstellungen des SR einstellst, dass Serienverzeichnisse angelegt werden sollen, dann wird dort das Cover erstellt. Ohne separates Verzeichnis pro Serie macht ein eigenes Verzeichnis für das Cover, aus meiner Sicht, keinen Sinn.

Oder habe ich deinen Bug falsch verstanden?

**Comment by cedi84** [comment]
super funktioniert jetzt
