### ISSUE TITLE
cover download

### ISSUE THREAD

**Issue by cedi84** [einfall/serienrecorder#49]
mit der aktuellen beta 3.3.0 wird kein cover heruntergeladen

**Comment by MacDisein** [comment]
Eben getestet, bei mir werden Cover runtergeladen - aber nicht alle Serien haben Cover.
Hast du ein Beispiel bei welchen Serien das Cover bei dir nicht heruntergeladen wird?!

**Comment by cedi84** [comment]
phu evtl. mache ich was falsch.
was muss ich genau machen damit die cover heruntergeladen werden?

serien z.b Bones, NCIS, Game of Thrones

**Comment by MacDisein** [comment]
"Cover anzeigen" in den globalen Einstellungen auf "ja" stellen und ein Verzeichnis auswählen in das die Cover heruntergeladen werden können (entsprechende Schreibrechte müssen gesetzt sein).
Dann werden die Cover heruntergeladen wenn irgendwo im SR eine Serie selektiert ist, z.B. In den Serien-Markern.

**Comment by cedi84** [comment]
ah ok, wusste nicht das ich jede serie einmal auswählen muss.

jetzt geht es.
