### ISSUE TITLE
alt stb-sender

### ISSUE THREAD

**Issue by cedi84** [einfall/serienrecorder#50]
obwohl in den einstellungen ausgewält ist das nur sender von der normalen liste verwendet werden sollen, sucht und erstellt der SR auch mit sendern der alt liste.

genaue erklärung: https://www.vuplus-support.org/wbb4/index.php?thread/85765-serien-recorder-3-2-6-11-02-2016/&postID=1419085#post1419085

**Comment by MacDisein** [comment]
Möchtest du auch genau das im Thread beschriebene Verhalten erreichen oder geht es dir um etwas anderes?

**Comment by cedi84** [comment]
du hast da gesagt das es mit der 3.3 evtl geht, aber der fehler ist noch immer da.
deshlab dachte ich melde ich den fehler hier 👍

**Comment by MacDisein** [comment]
Kannst du mir mal ein Log vom Auto-Check schicken in dem man das Problem sehen kann und deine SerienRecorder.db - damit ich das hier nachvollziehen kann.

**Comment by cedi84** [comment]
huhu
hier die beiden files: https://www.dropbox.com/s/p1x4yndo1mda7at/SerienRecorder.zip?dl=0

**Comment by MacDisein** [comment]
Ich habe mir da jetzt mal angesehen, laut Datenbank hast du bei allen Serien-Markern den Standard und bei "Der Bachelor" ist ebenfalls eingestellt, dass die "Standard Kanalliste" verwendet werden soll, du hast zwar auch eingeschaltet, dass die alternative Kanalliste bei Konflikten benutzt werden soll, aber das wirkt ja nur bei Konflikten.

Aus meiner Sicht müsste es funktionieren, wenn du für "Der Bachelor" als bevorzugte Kanalliste "Alternative Kanalliste" auswählst, und die Einstellung für "Verwende alternative Kanalliste bei Konflikten" auf "Nein".
Leider laufen scheinbar im Moment keine Folgen von der Bachelor, sodass im Log dazu auch nichts steht was bei diesem Serien-Marker passiert ist.

Oder habe ich das Problem immer noch nicht richtig verstanden - werden auch andere Serien auf "3+" aufgenommen, obwohl der gar nicht in der Standardliste ist?
Dann müsstest du im globalen Setup oder an den Serien-Marker die Option "Verwende alternative Sender bei Konflikten" abschalten. Sonst würde er bei einem Konflikt ja auch "3+" als Sender verwenden.

Leider taucht im Log auch "3+" nicht auf, sodass ich auch nicht erkennen kann was schief gelaufen ist.

**Comment by cedi84** [comment]
ups mien fehler weil es probleme gab habe ich beim bachelor auf standart gestellt und habe mal beim standard 3+ gelöscht.
ist vom testen.
genau dass was du beschrieben hast habe ich gemacht:
`_Aus meiner Sicht müsste es funktionieren, wenn du für "Der Bachelor" als bevorzugte Kanalliste "Alternative Kanalliste" auswählst, und die Einstellung für "Verwende alternative Kanalliste bei Konflikten" auf "Nein"._`

jedoch wird dann z.n navy CIS auch auf 3+ aufgenommen. und eben genau dass soll er nicht.

**Comment by MacDisein** [comment]
Aber hast du denn im globalen Setup eingestellt, dass bei Konflikten NICHT die alternative Kanalliste benutzt wird?

**Comment by cedi84** [comment]
ja habe ich. 
habe es jetzt soeben nochmals gemacht. 
das problem mit der version 3.3 ist so:
ist beim alt 3+ drin beim standard aber kein sender definiert finder sr kein sender.
