### ISSUE TITLE
Releas 3.3.0 und Beta 3.3.0 keine Daten

### ISSUE THREAD

**Issue by spinnentobii** [einfall/serienrecorder#51]
Hallo,

leider bekomme ich keine Daten egal ob ich mit dem Release 3.3.0 oder der Beta 3.3.0 probiere.

Ich bin schon lange mit an Board und habe 65 Serien eingespeichert, dass heißt sie dürfen mir ruhig glauben.

Neue Suchen finden auch keine Treffer so wie auch alte schon lang angelegte Serien wie zB Lindenstraße.

Ich hoffe sie können mit der Info etwas anfangen.

Grüße Tobias

**Comment by spinnentobii** [comment]
![img_0917](https://cloud.githubusercontent.com/assets/24364680/21058684/6f61ac1a-be3f-11e6-86e0-fe3d1cebf593.JPG)
![img_0918](https://cloud.githubusercontent.com/assets/24364680/21058688/6f67f052-be3f-11e6-84b4-5eea1d089419.JPG)
![img_0919](https://cloud.githubusercontent.com/assets/24364680/21058685/6f61bfb6-be3f-11e6-9ce4-e8519a29982a.JPG)
![img_0920](https://cloud.githubusercontent.com/assets/24364680/21058686/6f6314b0-be3f-11e6-98a4-bbef6ecd6e28.JPG)
![img_0921](https://cloud.githubusercontent.com/assets/24364680/21058683/6f6028d6-be3f-11e6-8565-c21cb576ce4e.JPG)
![img_0922](https://cloud.githubusercontent.com/assets/24364680/21058687/6f650888-be3f-11e6-9541-00cf54f7d84a.JPG)

**Comment by spinnentobii** [comment]
anbei ein paar Bilder
newnigma 2 daily 2016 
dm7080hd 
OS 4.2.7r1

**Comment by MacDisein** [comment]
Ja, das ist ganz normal im Moment

**Comment by spinnentobii** [comment]
Hallo, warum ist das ganz normal im Moment?

**Comment by MacDisein** [comment]
Weil Wunschliste gerade Performance Probleme hat und deswegen die Zugriffe des SerienRecorders einschränkt.

**Comment by schomi** [comment]
Auch wenn du es immer wiederholst, die Situation ist im Moment nicht zu ändern.
Einfach mal abwarten.

**Comment by ConberStamm** [comment]
Gibt es hier schon eine Lösung? Bei mir wird seit ein paar Tagen nur noch eine Serien aufgenommen, für alle anderen wird kein Timer erstellt oder gefunden.

**Comment by MacDisein** [comment]
Nein, noch nicht - Wunschliste arbeitet daran, danach muss das Plugin dann noch angepasst werden.

**Comment by cedi84** [comment]
macdisein, vieleich kannst du eine möglichkeit einbauen dass während dieser phase, user auf dem serienserver daten manuel eingeben können. so erreicht es hunderte von leute. und fehlt eine serie kann mann diese nachtragen.
wäre doch was oder??

ich z.b würde dies für viele meiner wichtigen seien sofort machen.....

**Comment by egn1** [comment]
Das habe ich mir auch schon überlegt.
Man könnte auch den RSS-Feed als Alternative zur Druckvorschau nehmen. Da steht zwar weniger drin, aber wichtig ist erst Mal dass die Aufnahmen wieder funktionieren.

**Comment by betonme** [comment]
Der RSS Feed funktioniert prinzipiell. Das hatte ich in einer alten Version des SeriesPlugins bereits implementiert.
Aber: Derzeit werden alle Anfragen des SerienServers blockiert, eine Umstellung ändert daran nichts.

Wir bekommen einen dedizierten Zugang zu Wunschliste.de, wann dieser aber bereitgestellt wird, kann ich nicht sagen...

**Comment by egn1** [comment]
Aber vielleicht könnte man tatsächlich eine manuelle Eingabemöglichkeit auf dem Server schaffen, dann könnte man die eigenen Serien mit Cut-and-Paste eintragen bis die Verbindung funktioniert.

**Comment by MacDisein** [comment]
Und so ein Webinterface ist mal eben mit einem Fingerschnipp gemacht - oder wie?
Auch wenn github eine Plattform für Softwareentwickler ist, habe ich den Eindruck, dass hier niemand die Ausmaße abschätzen kann, weder für den Entwicklungsaufwand eines solchen Interfaces noch was das manuelle Einpflegen der Daten angeht, wir haben z.Z. ca 25.000 Serien und etwas über 5 Millionen Datensätze mit Ausstrahlungsterminen in der Datenbank - ich wünsche schon jetzt viel Spaß beim Einpflegen der Daten per Copy and Paste.

**Comment by ConberStamm** [comment]
Was ich nicht verstehe: ich bekomme doch Serien angezeigt. Das sieht bei mir ziemlich komplett aus. Nur die Timer werden nicht gesetzt? Wenn ich die Ansicht ändere (aktuelle int. Serien) wird auch was runtergeladen. Eine Serie wird auch nach wie vor aufgenommen. Das ist die einzige, die ich auf RTLnitro aufnehme. Hängt das irgendwie mit der Kanalzuordnung zusammen?

**Comment by MacDisein** [comment]
Was du meinst ist die Serien-Planer Ansicht, die hat nichts mit der Timererstellung zu tun. Die Planer-Daten liegen noch für einige Tage im Voraus auf unserem SerienServer, deswegen können sie noch angezeigt werden. Für manche Serien liegen auch noch Ausstrahlungstermine vor.

**Comment by egn1** [comment]
Hallo MacDisein, es geht doch nicht darum Wunschliste zu ersetzen sondern eine Art Notbetrieb zu errichten. Es geht nur darum für existierende Serien irgendwie die Ausstrahlungstermine in den Server zu bekommen, damit die Aufnahmen weiter automatisch programmiert werden. Es geht auch nicht darum für alle 20000 Serien die Daten einzutragen sondern dass jeder in einer Art Crowd-Aktion, die für ihn relevanten Daten eintragen kann. Ich bin mir sicher wenn 100 Nutzer die Daten ihrer Serien eingetragen haben ist ein Großteil der wirklich genutzten Serien abgedeckt.

Das Interface zum Eingeben der RSS-Daten ist ein ganz einfaches Textfeld in das der Text der RSS Ausgabe beginnend mit Terminvorschau für "<Serie>" gepastet wird.

Der Text wird dann geparsed und in die Timer für die jeweilige Serie eingetragen.

Das Hauptproblem sehe ich eher hinsichtlich des Schutzes des Zugangs, insbesondere wer berechtigt ist irgendwelche Einträge vorzunehmen. Da fällt mir momentan keine vernünftige Lösung ein.

Eine zentrale Lösung wäre zwar für die Nutzer schöner. Aber wenn der jetzige Zustand noch länger anhält  werde ich mir eine lokale Lösung implementieren und die Daten für meine Serien in einer lokalen Datei ablegen.

**Comment by egn1** [comment]
Mir fällt noch gerade ein:
Du schreibst dass 5 Millionen Datensätze in der Datenbank vorhanden sind. Da ich annehme, dass diese alle noch weitgehend aktuelle sind, kann man diese nicht zugänglich machen?
Für bestehende Serien ändert sich an den Ausstrahlungsterminen kaum was, und wenn dann hat man halt Pech gehabt. Dies ist immer  noch besser als der jetzige Zustand.

**Comment by MacDisein** [comment]
Ich habe das schon verstanden, dass das Interface nicht WL ersetzen soll und nur für den Notbetrieb gebraucht wird.

Folgender Vorschlag: Ich stelle das Datenbank Schema des SerienServers zur Verfügung und du schreibst das einfache Textfeld und den Parser der die Daten in die Datenbank schreibt, dann lade ich das gerne auf den Server hoch.
Melde dich einfach per Mail oder poste hier noch mal, dann stelle ich dir das Datenbank Schema zur Verfügung.

Für den Zugriffschutz reicht ein Eintrag in der htaccess, da sehe ich keine große Probleme.

Die 5 Millionen Datensätze sind auch vergangene Ausstrahlungstermine, weil der SerienServer nicht nur den SerienRecorder sondern auch das SeriesPlugin mit Daten versorgt.

**Comment by 1xhabit** [comment]
Grundsätzlich sollte man Sagen!!! Was Passiert gerade und wer Opfert seine Zeit um das ganze am Laufen zu halten! Einen Riesen DAUMEN nach oben!!! Also Lassen wir die Jungs Ihr Hobby tun und meckern nicht, ist dann halt mal paar Tage so!!!

**Comment by ConberStamm** [comment]
Wie ist der aktuelle Stand? Hab gerade gesehen, dass viele neue timer setzt sind. Allerdings auch für bereits vorhandene Folgen. 
Die App selbst verabschiedet sich mit einem systemabsturz, wenn ich sie aufrufe.

**Comment by MacDisein** [comment]
Wir haben jetzt wieder Zugriff auf die Sendetermine von Wunschliste, alles andere funktioniert noch nicht oder nicht richtig.
Um den Absturz beim Starten zu verhindern, gibt es hier einen Patch.

**Comment by 1xhabit** [comment]
Naja, Super! Lieben Dank für Deine Mühe, habe denn patch gerade Installiert und siehe da es sind wieder Timer gesetzt worden. Aber was ich in letzter Zeit festgestellt habe, die Serien werden nicht 
mehr in die Serienordner geschoben. Aber ich weiss nicht ob das auch an meiner Box liegt und da was falsch ist was mit dem Plugin hier gar nix zu tun hat.

**Comment by michaelarlt** [comment]
Die Serien werden generell nicht verschoben sondern direkt im Zielordner aufgenommen. Kontrolliere am besten mal die Aufnahmepfade im Serien Marker. Das siehst du da direkt in der Liste und kannst relativ schnell durchscrollen fuer alle Serien. Mit einem sqlite Browser kannst du das auch direkt in der serienrecorder.db nachschauen

**Comment by wichy2000** [comment]
Super, das Ihr kurz vor Weihnachten noch eine neue Beta raushaut. Ich habe mir jetzt allerdings einen Fehler eingefangen. "Einige Plugins sind nicht verfügbar: Extentsions/serienrecorder Setup (No module named serienrecorder.SerienRecorder) Extensions/serienrecorder (No module named serienrecorder.plugin)" Die Fehlermeldung kommt, wenn ich über den VTI-Manager in die Extensions gehe.

Hab ich da was falsch kopiert? Ich habe die alten *.py *.pyo im serienrecorder-Ordner gelöscht und den aktuellen Inhalt über die *.py kopiert. Mir scheint, so als ob eine Datei fehlt.

**Comment by wichy2000** [comment]
Ich weiss, dass die 3.3 noch beta ist. 
Daher die Rückmeldung. Vielleicht hilft es bei der Weiterentwicklung.

Bei mir crashed jetzt leider das Plugin nachdem ich es mit `Exit` verlasse. 
Die GUI verabschiedet sich dann immer mit einem `green`-Screen. 
Hier die letzte Fehlermeldung aus dem `dvb2dvbapp2_crash.log`:

> [SerienRecorder] count channels 142
channels: false
Looking for embedded skin
warning, skin is missing element bt_green in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
warning, skin is missing element video in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
warning, skin is missing element bt_red in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
warning, skin is missing element bt_blue in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
warning, skin is missing element version in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
warning, skin is missing element bt_yellow in <class 'Plugins.Extensions.serienrecorder.SerienRecorder.serienRecMarker'>
action ->  SerienRecorderActions cancel
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 201, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10533, in readWebpage
    self.processPlanerData(planerData, False)
  File "/usr/lib/enigma2/python/Plugins/Extensions/serienrecorder/SerienRecorder.py", line 10540, in processPlanerData
    headDate = [data["date"]]
KeyError: 'date'
(PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x1de4b70>>,()) failed)
]]>`

**Comment by MacDisein** [comment]
Einfach die aktuellen Sourcen von GitHub nutzen, dort ist der Fehler behoben (3.3.1-beta)

**Comment by wichy2000** [comment]
Also ich hab jetzt folgendes getan: 
- opkg install enigma2-plugin-extensions-serienrecorder_3.3.0_all.ipk
- danach habe ich den aktuellen master-Zweig heruntergeladen und drüberkopiert

Ergebnis: Fehlermeldung in den Extensions: No module named serienrecorder/subprocess
Ich habe auch versucht alles aus dem aktuellen master drüber zu kopieren.

Mach ich etwas grundsätzlich falsch? Bisher reichte es, die git-sourcen per ftp in den Plugin-Ordner zu kopieren. Ich habe allerdings die pyo vorsichtshalber gelöscht. Die werden ja dann neu gebildet.

**Comment by MacDisein** [comment]
Durch die aktuellen Änderungen gibt es wohl zusätzliche Abhängigkeiten.
opkg install python-subprocess
Damit sollte das Problem gelöst sein.

**Comment by wichy2000** [comment]
Das war es! python-subprocess muss installiert sein, dann funktioniert die Version von heute.

Vielen Dank für die schnelle Hilfe. Ich werde die neuen Versionen testen und Feedback geben.

**Comment by nilschrishahn** [comment]
Hallo MacDisein,
Super das sich wieder was getan hat.
Folgende Fragen:
Bei der Suche findet der Serienrecorder gar nichts. Egal nach was ich suche, es kommt sofort 0 Treffer. Ist das im Moment noch so, oder woran kann es liegen?
Der Serienplaner zeigt auch nichts an. Es steht da zwar Lade Infos vom Web....aber geladen wird nichts. Es ist auch nicht abgestürzt. Auch normal bei der Version?

Danke für die tolle Arbeit.

**Comment by egn1** [comment]
Zitat MacDisein:
"Wir haben jetzt wieder Zugriff auf die Sendetermine von Wunschliste, **alles andere funktioniert noch nicht oder nicht richtig**."

**Comment by spinnentobii** [comment]
Teste gerade die Beta 3.4.0 entweder ist gerade ganz Deutschland im Netz am streamen? denn die Antwortzeiten sind extrem lang

**Comment by spinnentobii** [comment]
Werde es jetzt mit dem TV Planer testen aber wo finde ich den Punkt  ""Autocheck Zeit beta 3.4.0""

**Comment by michaelarlt** [comment]
@spinnentobii Autocheck ist auf Seite zwei der Suchlauf fuer die automatische Suche. Wenn ich alles richtig verstanden habe sollte man den auf 6 Uhr stellen wenn die Mail um 5 Uhr verschickt wird.
![tv_planer](https://cloud.githubusercontent.com/assets/18514062/21472859/a53a88c0-caec-11e6-8302-bc51ac2ccac0.jpg)
Ich kanns auch erst ab morgen testen

**Comment by spinnentobii** [comment]
ich suche die Einstellung wie im Punkt ---"Die Autocheck Zeit sollte man auf etwa 1 h nach der Zeit einstellen zu der die TV-Planer Email eintrifft."---- beschrieben.

**Comment by MacDisein** [comment]
Die Option heißt "Uhrzeit für automatischen Suchlauf"

**Comment by egn1** [comment]
Da der SerienServer jetzt zusammen mit dem neusten 3.4 Beta funktioniert schließe ich hier.

**Comment by ConberStamm** [comment]
Naja, nur mit dem Umweg über die Email. Im Serienrecorder kann man keine Serien anzeigen und keine Marker setzen.

**Comment by egn1** [comment]
Hast Du schon einen Update gemacht?

**Comment by ConberStamm** [comment]
Ja, 3.4.0-Beta

**Comment by MacDisein** [comment]
Und welche essentielle Funktion funktioniert in der aktuellen Betaversion die den SerienRecorder unbenutzbar macht?

**Comment by michaelarlt** [comment]
Bei mir werden Serien angezeigt und Marker gehen ebenso.
Klasse Arbeit von euch Dev's

**Comment by ConberStamm** [comment]
Das scheint jetzt falsch rüber gekommen zu sein. Dank der Beta kann ich den Serienrecorder wieder benutzen. Serien trage ich über die Email Funktion ein. Funktioniert gut. Somit werden keine Folgen verpasst. Danke für die schnelle Reaktion! 
Was noch nicht geht: es werden keine Serien angezeigt, somit lassen sich im Plugin keine neuen Serien hinzufügen. "Fehler beim Abrufen der SerienPlaner-Daten"

**Comment by egn1** [comment]
Serien-Planer Daten wird es auch nicht mehr in der Form wie früher geben, da die Daten von Wunschliste nicht mehr nutzbar sind. Aber man kann neue Marker auch über die Suche im SR eintragen und MacDisein hat mittlerweile auch schon was überlegt um die Serien-Planer Anzeige mit Informationen zu füllen.

Bitte melde Dich für User Support im VU+ oder Dreambox Forum an, da wir hier im Git nur Entwickler Themen diskutieren wollen. Danke.
