### ISSUE TITLE
Zuweisung Sender erzeugt einen Crash 

### ISSUE THREAD

**Issue by ConberStamm** [einfall/serienrecorder#52]
Seit dem Update ruf die 3.3.0 ist die Senderzuweisung in den Einstellungen über Menü erreichbar. Das führt bei mir zu einem Absturz. 

![img_0836](https://cloud.githubusercontent.com/assets/24553246/21156944/eeea34b2-c177-11e6-9a84-cd4331fffe18.JPG)
![img_0838](https://cloud.githubusercontent.com/assets/24553246/21156947/ef2d70e2-c177-11e6-8f43-744b6d44258d.JPG)
![img_0840](https://cloud.githubusercontent.com/assets/24553246/21156946/ef1d55b8-c177-11e6-884e-52de676f999a.JPG)

**Comment by MacDisein** [comment]
Behoben in d1a534bea625932e23d6b9ce9a22f2d997caa669

**Comment by ConberStamm** [comment]
Was bedeutet das? Warten auf ein Update?

**Comment by MacDisein** [comment]
Was soll ich sagen, die Daten für den SerienRecorder kommen von Wunschliste, dazu zählt auch die Senderliste - im Moment funktioniert das Plugin nicht. Wenn die Daten wieder empfangen werden können, dann funktioniert es wieder. Du kannst aber auch den Patch installieren und dann gibt es keinen Crash mehr beim Aufrufen der Senderliste, es wird dir aber nicht helfen, weil im Moment keine Daten von Wunschliste kommen.

**Comment by ConberStamm** [comment]
Na dann warte ich doch einfach noch eine Weile. Danke für die schnelle Reaktion!
