### ISSUE TITLE
Question: Dokumentation

### ISSUE THREAD

**Issue by michaelarlt** [einfall/serienrecorder#54]
Welche Dokumentation soll eigentlich die aktuelle sein?
Auf http://einfall.github.io/serienrecorder/SerienRecorder.html liegt ja die ausfuehrliche Doku allerdings ist die etwas veraltet. Unter https://github.com/einfall/serienrecorder/wiki findet man einen kleinen Auszug der aber auch bearbeitet werden kann von "Freiwilligen"
Gibt es da von eurer Seite eine bevorzugte Location oder habt ihr das bisher aussen vor gelassen?
Ich kann zwar net Vollzeit an ner Aktualisierung der Doku mitwirken, habe aber Interesse diese nach und nach zu aktualisieren. Falls eurerseits Interesse besteht diese zugaeglich zu machen fuer Freiwillige, lasst es mich bitte wissen.

**Comment by koivo** [comment]
Ich dachte die ist hier im git unter help mit drin?
https://github.com/einfall/serienrecorder/tree/master/src/Help

**Comment by MacDisein** [comment]
Im Moment sind alle Dokumentationen veraltet, ich habe lokal eine neue Version, die aber noch nicht fertig ist, die ist allerdings in purem HTML geschrieben, wenn das kein Problem ist, dann kann ich die zugänglich machen, es wird sich aber noch einiges verändern in nächster Zeit, weil wir ja leider nicht mehr alle Informationen von Wunschliste bekommen und deshalb das eine oder andere umgebaut werden muss.

**Comment by michaelarlt** [comment]
danke @koivo fuer die Info. Ja dann koennte man diese ja aktualisieren mit dem Stand welche @MacDisein derzeit hat. Ich bin zwar kein html-crack aber mit notepad++ komm ich zurecht ;)
Ist auch kein Problem wenn die derzeit auch nicht zu den Features passt welche SerienRecorder bietet, gerade in Bezug auch Wunschliste. Sobald ein paar Freiwillige da mitwirken wird die ziemlich schnell aktuell sein und auch "leben".
Dann koennte man im Wiki nur eine Verlinkung einfuegen zur Doku und @einfall koennte auf seiner Seite auch eine Verlinkung setzen. Dann haette man schonmal eine zentrale Version die auch aktualisiert werden kann.

**Comment by MacDisein** [comment]
Hier die unvollständige, neue Version der Dokumentation, wenn jemand sie fortsetzen möchte:
[serienrecorder-pages.zip](https://github.com/einfall/serienrecorder/files/682527/serienrecorder-pages.zip)
