### ISSUE TITLE
TV-Planer funktioniert der?

### ISSUE THREAD

**Issue by spinnentobii** [einfall/serienrecorder#57]
Hallo, funktioniert der TV-Planer wirklich? 
Ich habe eine gmx.de EMailadresse und es gab noch nie einen erfolgreichen Import. Emails werden von der Webseite an GMX verschickt! 
Wie kann ich teste, ob meine Einstellungen im Serienrecorder richtig sind. 

meine Settings
INBOX
imap.gmx.de
Port 00993
Abruf 02:00

Wunschliste Programmbeginn 00:00
TV-Planer aktiv

**Comment by MacDisein** [comment]
Du kannst in der SerienMarker Ansicht mit der Taste 5 eine IMAP-Check durchführen. Der gibt seine Ergebnisse im Log aus (Taste 0).
Der Check führt mit den in den Einstellungen eingetragenen Werten einen Login durch, listet dann die Mailbox Struktur auf dem Server auf, und gibt die Anzahl der TV-Planer Mails in der angegebenen Mailbox aus.

Ich empfehle übrigens, dass du dich entweder im I-have-a-dreambox oder im vuplus-support Forum anzumelden und dort deine Fragen im entsprechenden Thread los zu werden, so müssen wir nicht auch noch hier, in einem Entwicklerforum Support für Enduser leisten.

**Comment by spinnentobii** [comment]
Vielen Dank für die Auskunft und mit der neuen Version Beta Version 3.4.0.1 funktioniert jetzt der IMAP Check: OK (2) trotzdem wird keine Serie aus der Email angelegt.

**Comment by egn1** [comment]
Ohne LOG können wir Dir nicht helfen.

**Comment by spinnentobii** [comment]
anbei der log mit allen Einträgen
ob automatisch oder manuell
![08-01-_2017_07-27-33](https://cloud.githubusercontent.com/assets/24364680/21747809/18cc3676-d574-11e6-8e68-9a573adef55e.jpg)
![08-01-_2017_07-15-06](https://cloud.githubusercontent.com/assets/24364680/21747785/cae1adce-d573-11e6-9fe2-4c9ba4c3a418.jpg)
![08-01-_2017_07-16-31](https://cloud.githubusercontent.com/assets/24364680/21747786/cae45e2a-d573-11e6-83c1-ac856393af02.jpg)
[SerienRecorder.txt](https://github.com/einfall/serienrecorder/files/691912/SerienRecorder.txt)

**Comment by MacDisein** [comment]
Das Log ist von einem manuellen Auto-Check ohne TV-Planer.
Du musst den Auto-Check mit TV-Planer starten (in der Serien-Marker Ansicht die EPG/INFO Taste lang drücken).

Ich möchte noch mal darauf hinweisen, dass das hier eine Platform für Entwickler ist, und hier eigentlich kein Enduser Support stattfinden kann. Du solltest dich also zukünftig bei Bedienungsproblemen entweder im VU+ Support oder im IHAD Forum melden, dort geben wir Enduser Unterstützung

**Comment by spinnentobii** [comment]
ich bin hier um auf eventuell Fehler hinzuweisen.
Die anderen Plattformen kenne ich.

War heute früh der falsche Log. Anbei die richtige Datei mit auslesen der Email aber ohne Serie oder Timer anzulegen von Deutschlandbilder.
[SerienRecorder.txt](https://github.com/einfall/serienrecorder/files/692034/SerienRecorder.txt)

**Comment by MacDisein** [comment]
Deutschlandbilder ist eine Serie ohne Staffel und Episoden Nummern, solche Arten von Serien sind ein Problem für den SerienRecorder, weil nur einmal ein Timer mit S00E00 angelegt wird. Für solche Arten von Serien ist der SerienRecorder nicht geeignet. Dafür solltest du entweder einen Wiederholgstimer oder Auto-Timer verwenden.

**Comment by spinnentobii** [comment]
Würde gerne noch mit einer Spende Danke sagen und dann schließen wir das Ticket.
