### ISSUE TITLE
Senderauswahl bei Marker funtioniert nicht

### ISSUE THREAD

**Issue by vfbler** [einfall/serienrecorder#59]
Eingestellte Sender bei Markern werden nicht berücksichtigt, es wird immer von allen Sendern aufgenommen. Aktuell passiert das bei "Der Alte". Als Sender ist ZDF eingestellt, er erstellt aber auch Timer auf ZDF_neo.

**Comment by vfbler** [comment]
Eingestellte Sender bei Markern werden nicht berücksichtigt, es wird immer von allen Sendern aufgenommen. Aktuell passiert das bei "Der Alte". Als Sender ist ZDF eingestellt, er erstellt aber auch Timer auf ZDF_neo.

**Comment by MacDisein** [comment]
Kannst du bitte mal das passende SerienRecorder Log bereitstellen.

**Comment by vfbler** [comment]
Hier das Log:

> 
---------' Starte Auto-Check um 04.01.2017 - 23:21:30 (auto)'-------------------------------------------------------------------------------

STB Type: duo2
Image: 11.0.1 / Release 11.0.1 2015-11-17
SR Version: 3.4.0-beta
Skin Auflösung: 1280 x 720

DEBUG Filter: Senderliste Episoden Added Disk Tageszeit Zeitlimit Timer Debug 

Laden der SerienPlaner-Daten gestartet ...
Fehler beim Abrufen und Verarbeiten der SerienPlaner-Daten [0]

Fehler beim Abrufen und Verarbeiten der SerienPlaner-Daten [1]

Fehler beim Abrufen und Verarbeiten der SerienPlaner-Daten [2]

Fehler beim Abrufen und Verarbeiten der SerienPlaner-Daten [3]

... Laden der SerienPlaner-Daten beendet

Berücksichtige Ausstrahlungstermine zwischen 04.01.2017 - 23:21 und 06.01.2017 - 23:21
Berücksichtige Wiederholungen zwischen 04.01.2017 - 23:21 und 14.01.2017 - 23:21

---------' Laden TV-Planer E-Mail '---------------------------------------------------------------

Ab dem 05.01.2017 05:00 Uhr wurden die folgenden Sendungen gefunden:

...
' Der Alte - S00E204 - Am hellichten Tage - 'ZDFneo' '
...

---------' Verarbeite Daten vom Server '---------------------------------------------------------------

%kein entsprechender Eintrag%

---------' Erstelle Timer '-------------------------------------------------------------------------------

%kein entsprechender Eintrag%

---------' Aktualisiere Timer '-------------------------------------------------------------------------------

%kein entsprechender Eintrag%

17/17 Serie(n) sind vorgemerkt davon wurde(n) 5 Timer erstellt und 0 Timer aktualisiert.
---------' Auto-Check beendet (Ausführungsdauer: 13.925 Sek.)'---------------------------------------------------------------------------

---------' Verarbeite TV-Planer E-Mail '-----------------------------------------------------------

%kein entsprechender Eintrag%

---------' Erstelle Timer '-------------------------------------------------------------------------------

...
Versuche Timer anzulegen: ' Der Alte - S00E204 - Am hellichten Tage - /media/hdd/movie/ '
Timer angelegt: Der Alte S00E204 - Am hellichten Tage
' Der Alte - S00E204 - Am hellichten Tage ' - Timer wurde angelegt -> 05.01.2017 - 14:30 Der Alte - S00E204 - Am hellichten Tage @ zdf_neo HD
...

---------' Aktualisiere Timer '-------------------------------------------------------------------------------

...
' Der Alte - S00E204 - Am hellichten Tage - /media/hdd/movie/ '
   Timer muss nicht aktualisiert werden @ ZDFneo
...
   
34/34 Serie(n) sind vorgemerkt davon wurde(n) 6 Timer erstellt und 0 Timer aktualisiert.
---------' Auto-Check beendet (Ausführungsdauer: 18.752 Sek.)'---------------------------------------------------------------------------

Verbleibende Zeit bis zum nächsten Auto-Check: 24:08 Stunden

**Comment by MacDisein** [comment]
Ok, dann interpretiere ich das Log so, dass das Problem im Zusammenhang mit dem TV-Planer entsteht, dann muss ich die Lösung an @egn1 überlassen.

**Comment by egn1** [comment]
Aus meiner Sicht ist das normales Verhalten mit dem TV-Planer, wenn durch die vorher mit dem SerienServer stattfindende Verarbeitung kein Timer für die Sendung angelegt wurde. Die entsprechenden Abschnitte oben sind ja leer. Dann wird ohne weitere Information vom SerienServer der Timer auf jeden Fall so angelegt wie sie in der TV-Planer E-Mail steht.

Warum die Sendung vorher nicht mit dem SerienServer angelegt wird könnt auch mit der Abfrage der SerienID für die Sendung zusammenhängen. Momentan kommt da anscheinend manchmal 0 zurück.

**Comment by vfbler** [comment]
Meine Sendereinschränkung auf ZDF steht aber in meiner DB, das lege ich im Programm fest. Muss da nicht die Mail-Logik gegen diese Einschränkung prüfen, bevor der Timer angelegt wird?

**Comment by MacDisein** [comment]
Es wurde ja aber für den Serien-Marker "Der Alte" der Sender auf "ZDF" beschränkt, deswegen wird durch die Verarbeitung durch den SerienServer auch kein Timer angelegt.
Das musst du auch berücksichtigen wenn du später die Timer aus der TV-Planer E-Mail anlegst.

**Comment by egn1** [comment]
Ok, ich bin bisher davon ausgegangen dass eine Sendung die auf mehreren Sendern kommt vorher schon durch die Abfrage auf dem SerienServer auf dem richtigen Sender programmiert wurde und dann über den TV-Planer nicht mehr programmiert wird, und alte Folgen entweder schon über die Timer oder aber die Staffelbeschränkung weg geblendet sind.

Dann muss ich wohl auch beim TV-Planer alle Sender prüfen.

**Comment by vfbler** [comment]
Man könnte die Mail-Logik soweit erweitern, dass sie quasi autonom läuft. Dann könnte man sogar die Timeranlage mit Server per Option ausschalten. Das würde eine Menge Traffic sparen.

**Comment by 1xhabit** [comment]
MoinMoin, also habe das Update gerade installiert, kommt aber die Meldung Fehler beim abrufen der Daten!

**Comment by egn1** [comment]
@vfbler 
Die TV-Planer Funktion ist heute schon eigenständig. Allerdings verliert man dadurch den Vorteil zukünftige Sendungen zu programmieren und insbesondere auch Tuner Konflikte durch das Aufnehmen von Wiederholungen aufzulösen. Dadurch dass nur noch Serien gescannt werden die in den TV-Planer E-Mails auftauchen wird der Datenverkehr schon auf geschätzt 1/10 reduziert. 

@1xhabit 
Bitte den Inhalt der LOG Datei bereitstellen.

**Comment by vfbler** [comment]
Eine Verständnisfrage. Wenn ich beim Server als Zeitraum nur 1 Tag angebe, macht er dann nicht dasselbe wie die Mail? Oder sucht er trotzdem in der Zukunft, um Timerkonflikte aufzulösen? Dann würde man das natürlich verlieren. Da aber fast alles in zich Wdh pro Woche kommt, würde irgendwann doch alles aufgenommen ;-)

**Comment by MacDisein** [comment]
Es gibt ja zwei Einstellungen im SerienRecorder - einmal die Anzahl Tage für die Timer angelegt werden sollen, z.B. "4" und die Anzahl Tage um nach Wiederholungen zu suchen, z.B. "7".
Dann werden also für die nächsten vier Tage Timer erstellt, wenn es in dieser Zeit einen Konflikt gibt, dann guckt der SR ob eine der Sendungen die in Konflikt stehen innerhalb der nächsten 7 Tage wiederholt werden, wenn ja, dann legt der SerienRecorder diese Sendung nicht an, sondern legt erst ein paar Tage später die Wiederholung an.

Du müssest also den Zeitraum für beide Werte auf einen 1 Tag stellen um das Verhalten wie in der Mail zu haben.

Solange Wunschliste also immer nur die Sendetermine für einen Tag in ihren TV-Planer Mails hat und nicht alle Termine für die nächsten x Tage kann der TV-Planer den normalen SerienRecorder SerienServer Modus nicht ablösen.

**Comment by egn1** [comment]
Die Senderauswahl sollte mit dem neusten Update funktionieren.
