### ISSUE TITLE
Fresh OpenATV Image & Serienrecorder 3.3

### ISSUE THREAD

**Issue by 1xhabit** [einfall/serienrecorder#60]
Also, erst mal moin, es ist mitten in der Nacht! Ich dachte ok, neuer Serienrecorder, machst Du mal einen Clean Install. Was passiert! Also alles lässt sich fein Installieren. Nur mit einem Fresh Image kommt die Meldung dem Serienrecorder fehlt das Sqlite3 Modul. Nächstes Problem, bekannt als CI+ Problem nach dem 26.12.2016 Image. Wird der Serienrecorder installiert, funzt hinter kein CI+ weil 
auf eine neuere Version Image geupt wird. Somit ist CI+ Futsch. Hm, ich versuche jetzt die 3.2 zuerst 
zu installieren und dann per ftp das neu git drüber. gibt es andere Lösungen damit damit die box beim image von 24.12.2016 bleibt?

**Comment by 1xhabit** [comment]
So, der aktuelle Stand ist: Clean Install mit 5.3 image. Zuerst denn 3.2 Serienrecorder installiert. Einmal den Setup gestartet. Dann denn 3.3 aus dem Github per ftp drüberkopiert. Box Läuft! Serienrecorder auch sowie ci+. Einzige Problem auch das kopieren der Timer.xml nach /etc/enigma2 hilft nicht. Die Timer bleiben Verschwunden.

**Comment by egn1** [comment]
Deine Probleme haben nichts mit dem SerienRecorder zu tun. Bitte diskutiere diese in dem relevanten Forum für Dein Image.
