### ISSUE TITLE
Crash mit Version von 20170110 beim Aufruf der Senderaktualisierung

### ISSUE THREAD

**Issue by Burny4600** [einfall/serienrecorder#62]
[enigma2_crash_1484076018.zip](https://github.com/einfall/serienrecorder/files/697143/enigma2_crash_1484076018.zip)
Die Senderliste wurde nicht ordnungsgemäß von der Vorversion übernommen.
Beim Aufruf der Senderlisten Aktualisierung crasht die Box.

**Comment by MacDisein** [comment]
Sehe ich das richtig, dass du beim ersten Mal versucht hast nach einem manuellen Auto-Check die Sendeliste zu bearbeiten und beim zweiten Mal hast du das SerienRecorder Setup Plugin verwendet?

**Comment by Burny4600** [comment]
Habe beide Male im Setup des SR den Aufruf für die Senderlisten Aktualisierung ausgeführt, weil bei den definierten Serienaufzeichnungen keine zugehörigen Sender gefunden wurden. 

 

Mit freundlichen Grüßen

  

_________________________________

Christian Schmidt

Lichtenegger Straße 31, A-4600 Wels

Tel.:                 +43-7242-26786-0

Fax:                 +43-7242-26786-33

Mobil:             +43-664-3366277

Email:              christian.schmidt@ccs-media.at

Website:         http://www.ccs-media.at

Wetter Wels:  http://www.ccs-media.at/lwn/

 

Haftungsausschluss:

Obwohl wir uns bemüht haben, Ihnen fehler- und virenfreie Daten zur Verfügung zu stellen, übernehmen wir keine wie immer geartete Haftung oder Garantie, dass die zur Verfügung gestellte Daten fehler- oder computervirenfrei sind, arbeitet und entsprechend funktioniert.

Insbesondere übernehmen wir auch keine Haftung für entgangenen Gewinn, direkte oder indirekte Schäden, materielle oder immaterielle Schäden oder Mangelfolgeschäden, die durch die Daten oder ihren Inhalt verursacht werden.

Mit der Verwendung der Daten stimmen Sie diesem Haftungsausschluss zu.

 

 

 

Von: MacDisein [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. Jänner 2017 22:26
An: einfall/serienrecorder
Cc: Burny4600; Author
Betreff: Re: [einfall/serienrecorder] Crash mit Version von 20170110 beim Aufruf der Senderaktualisierung (#62)

 

Sehe ich das richtig, dass du beim ersten Mal versucht hast nach einem manuellen Auto-Check die Sendeliste zu bearbeiten und beim zweiten Mal hast du das SerienRecorder Setup Plugin verwendet?

**Comment by MacDisein** [comment]
Du kannst die Einstellungen des SerienRecorders aufrufen wenn du im SerienRecorder die MENÜ Taste drückst.

**Comment by Burny4600** [comment]
Genau so hatte ich es gemacht. Mit der Menü Taste das Setuo aufgerufen.

**Comment by MacDisein** [comment]
Dann muss es irgendwas sein, dass du davor im SerienRecorder gemacht hast.
Kannst du die Schritte mal beschreiben die ich machen muss um das Problem zu reproduzieren, ich konnte das gestern Abend und jetzt eben nicht zum Absturz bringen?

**Comment by Burny4600** [comment]
So ich denke ich habs.
Wenn ich über Erweiterungen => Serienrecorder => Menü => Menü reingehe funktioniert es.
Gehe ich über Erweiterungen => Serienrecorder (Setup) => Menü rein passiert der Crash.

**Comment by MacDisein** [comment]
Na, dann wäre das ja geklärt!
