### ISSUE TITLE
Spielfilme in TV-Planer ignorieren

### ISSUE THREAD

**Issue by pr0j3ctx** [einfall/serienrecorder#64]
Hallo.

Der TV-Planer hat bei mir einen Spielfilm als Serie hinzugefügt und die Aufnahme als S00E00 hinzugefügt. Einerseits schön das er aus aufnimmt. Andererseits habe ich eine unnütze Serie im Serienmarker.

Könnt ihr derartige Einträge aus der E-Mail ignorieren? Oder am besten einfach einen manuellen Timer anlegen und gut ist?

Hier der Teil der Mail mit dem Film. Im Link zur Wunschliste ist ein /spielfilm/ anstelle von /serie/ drin. Danach könnte man sicherlich filtern.

[Auszug aus der Mail](https://gist.github.com/pr0j3ctx/d2f132b690cb0707281abe91f66801ba)

Danke und Gruß
pr0

**Comment by MacDisein** [comment]
Spielfilme sind erst seit ein paar Wochen offiziell bei Wunschliste vorhanden. Da es für Spielfilme keine Staffel-/Episodennummer gibt, erstellt der SerienRecorder Timer mit S00E00.
Es gab schon einige die sich gefreut haben, dass man jetzt auch Filme über WL bekommt und der SerienRecorder dafür auch Timer erstellt.

Ich halte es für sinnvoll in den Einstellungen die Option zu haben, Spielfilme ignorieren zu können. Im Moment bin mir auch noch nicht sicher, ob das "Problem" nur beim Einsatz vom TV-Planer auftritt. Bzw. wie der SerienRecorder Spielfilme erkennen soll, wenn sie nicht über den TV-Planer kommen.

**Comment by pr0j3ctx** [comment]
Ich bin aktuell geteilter Meinung. Irgendwie finde ich es gut das die Filme aufgenommen werden. Andererseits stört mich der Eintrag im Serienmarker.
Die Benennung S00E00 ist für mich auch ok. Vielleicht gibt es hier eine schönere Lösung. 
Das ganze soll auch mehr ein Merker sein, da ihr aktuell sicherlich genug zu tun habt.

**Comment by egn1** [comment]
Wie MacDisein schon schrieb, gibt es einige die die Programmierung von Spielfilmen über WL gerne hätten. Das jetzige Verhalten ist erst Mal nur das Gleiche als wenn man eine Serie ohne Staffel/Episoden hätte. Das Ziel ist dann dass der SerienMarker nach der Programmierung des Timers wieder gelöscht wird, aber der Timer aber in der Timerliste verbleibt und so Wiederholungen nicht mehr aufgezeichnet werden. Die Implementierung wird aber noch etwas dauern.

**Comment by schomi** [comment]
Mir gefällt das, weil solche Filme öfters Pilot Filme zur Serie sind. Wenn man die nicht haben will, kann man die doch löschen.

**Comment by egn1** [comment]
Mit der aktuellen Version kann man einstellen ob Spielfilme in der TV-Planer E-Mail aufgenommen werden sollen oder nicht. In der nächsten Version wird das dann auch für Serien gehen. So kann man dann wenn man mehrere Boxen hat die Aufnahmen entsprechend verteilen.
