### ISSUE TITLE
STB Sender nicht gefunden. Nach wie vor Absturz bei Sender Aktualisierung.

### ISSUE THREAD

**Issue by Burny4600** [einfall/serienrecorder#65]
[SerienRecorder.zip](https://github.com/einfall/serienrecorder/files/702678/SerienRecorder.zip)

**Comment by MacDisein** [comment]
Ich verstehe dein Problem nicht ich hatte in dem ersten Bug den du gestern gemeldet hattest geschrieben:

> Sehe ich das richtig, dass du beide Male das SerienRecorder Setup Plugin verwendet hast?
Das gibt es nicht mehr - und sollte von dir gelöscht werden.
In den alten Plugin Installern gab es noch einen Fehler, dass das Plugin nicht gelöscht wurde.

Du darfst die Senderzuordnung also nicht über das SerienRecorder Setup Plugin aufrufen, sondern direkt aus den SerienRecorder Einstellungen.

Zu deinem zweiten Problem:
"STB Sender nicht gefunden" bedeutet, dass für die Sendung auf einem Sender ausgestrahlt wird, die du keinem Sender auf deiner Box zugeordnet hast.

**Comment by egn1** [comment]
MacDisein hat noch vergessen zu erwähne, dass solche Nutzungsprobleme bitte entweder im VU+ Forum oder im Dreambox Forum gemeldet werden sollten. Dort wird auch User-Support geleistet. Hier sollen sich nur die Entwickler austauschen. Danke!

**Comment by Burny4600** [comment]
OK.

Jetzt habe ich es verstanden worum es geht mit SerienRecorder Setup Plugin.

 

Das mit der Senderzuordnung passt aber, darum verstehe ich diese Meldung nicht.

Wenn ich über Serienrekorder => Menü => Menü die Senderliste aufrufe sind die benötigten Sender aber richtig zugeordnet.

 

 

Von: MacDisein [mailto:notifications@github.com] 
Gesendet: Donnerstag, 12. Jänner 2017 21:17
An: einfall/serienrecorder
Cc: Burny4600; Author
Betreff: Re: [einfall/serienrecorder] STB Sender nicht gefunden. Nach wie vor Absturz bei Sender Aktualisierung. (#65)

 

Ich verstehe dein Problem nicht ich hatte in dem ersten Bug den du gestern gemeldet hattest geschrieben:

Sehe ich das richtig, dass du beide Male das SerienRecorder Setup Plugin verwendet hast?
Das gibt es nicht mehr - und sollte von dir gelöscht werden.
In den alten Plugin Installern gab es noch einen Fehler, dass das Plugin nicht gelöscht wurde.

Du darfst die Senderzuordnung also nicht über das SerienRecorder Setup Plugin aufrufen, sondern direkt aus den SerienRecorder Einstellungen.

Zu deinem zweiten Problem:
"STB Sender nicht gefunden" bedeutet, dass für die Sendung auf einem Sender ausgestrahlt wird, die du keinem Sender auf deiner Box zugeordnet hast.

**Comment by Burny4600** [comment]
Anbei die DB.

 

Von: MacDisein [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Jänner 2017 17:36
An: einfall/serienrecorder
Cc: Burny4600; Author
Betreff: Re: [einfall/serienrecorder] STB Sender nicht gefunden. Nach wie vor Absturz bei Sender Aktualisierung. (#65)

 

Dann würde ich dich bitte mir deine SerienRecorder.db zur Verfügung zu stellen, damit ich das hier nachstellen kann.

**Comment by MacDisein** [comment]
Kein Anhang

**Comment by Burny4600** [comment]
Anbei nochmals ein Versuch.
[SerienRecorder.zip](https://github.com/einfall/serienrecorder/files/704956/SerienRecorder.zip)

**Comment by MacDisein** [comment]
Der Sender "Syfy" ist nur als "Alternativer Sender" zugewiesen, deswegen wird der nicht gefunden. Wie der Name schon sagt, ist ein alternativer Sender ein Sender der als Alternative zu einem primären Sender zugewiesen ist, z.B. die SD Variante eines HD Senders. Solange du keinen primären Sender zugewiesen hast, macht es keinen Sinn einen alternativen Sender zu setzen.
Ich schlage vor, ich mache hier zu, das sind alles Anwendungsfehler und keine Bugs in der Software, wie @egn1 schon geschrieben hat, zukünftig solche Fragen bitte in den entsprechenden Support Foren posten.

**Comment by Burny4600** [comment]
Das ist aber kein alternativer Sender. 
Laut der Senderliste ist ein Sender zugewiesen. Bei dem aufzuzeichnenden Programm ist dort auch kein alternativer Sender zugewiesen.
Es habe seit über zwei Jahren den SR im Einsatz und es gab vorher nie Probleme.
Erst seit den notwendigen Änderungen wegen Wunschliste.de tritt diese Meldung auf bei der Timer Anlage.
Wo soll ich da noch etwas ändern? 
Mag schon sein das es kein Bug ist, aber irgendwo hat sich grundsätzlich etwas geändert seitdem die Senderliste über Menü => Menü zu verwalten ist. 
Ich habe jedenfalls noch keine Lösung gefunden.

**Comment by MacDisein** [comment]
Ich habe mal einen Screenshot gemacht, von deiner Senderzuordnung.
Bei dir sind fast alle Sender als alternativer Sender zugewiesen (steht auch oben als Spaltenüberschrift "Alt. STB Sender" - das ist die Abkürzung für "Alternativer Sender". Und in der Spalte links daneben (STB Sender) ist für "Syfy" kein Sender zugeordnet. Und deswegen steht im Log bei Sendungen die auf "Syfy" getimert werden sollen, dass kein STB Sender gefunden wurde, weil es eben  nur einen "alternativen Sender" gibt.
![screenshot](https://cloud.githubusercontent.com/assets/8401876/21956431/ca6f17d4-da80-11e6-8a9b-a9070e8aa634.png)

**Comment by Burny4600** [comment]
Es lässt sich aber die Senderzuordnung nicht anders definieren.

Wenn ich die Sendereinträge lösche hilft das auch nichts.

Wenn ich die Sender aus den definierten Favoriten übernehme werden die Sender immer rechts eingetragen.

In der mittleren Spalte befand sich noch nie ein Sender.

ZB.: Beim Web-Sender Syfy ist der primäre Sender der Syfy HD. Alternativ wenn nicht anders möglich wäre es der Syfy.

Da ich aber keine alternativen Sender verwende werden diese auch nicht benötigt.

 

Es hat ja vor der Änderung der Senderlisten Bearbeitung unter Menü => Menü früher auch ohne Problem funktioniert.

LG

Chris

 

Von: MacDisein [mailto:notifications@github.com] 
Gesendet: Samstag, 14. Jänner 2017 17:42
An: einfall/serienrecorder
Cc: Burny4600; Author
Betreff: Re: [einfall/serienrecorder] STB Sender nicht gefunden. Nach wie vor Absturz bei Sender Aktualisierung. (#65)

 

Ich habe mal einen Screenshot gemacht, von deiner Senderzuordnung.
Bei dir sind fast alle Sender als alternativer Sender zugewiesen (steht auch oben als Spaltenüberschrift "Alt. STB Sender" - das ist die Abkürzung für "Alternativer Sender". Und in der Spalte links daneben (STB Sender) ist für "Syfy" kein Sender zugeordnet. Und deswegen steht im Log bei Sendungen die auf "Syfy" getimert werden sollen, dass kein STB Sender gefunden wurde, weil es eben nur einen "alternativen Sender" gibt.
 <https://cloud.githubusercontent.com/assets/8401876/21956431/ca6f17d4-da80-11e6-8a9b-a9070e8aa634.png> screenshot

**Comment by MacDisein** [comment]
Es hat mit alten Version falsch funktioniert - seit der Version 3.3.0 funktioniert es richtig, deswegen musst du jetzt die Sender als primäre Sender zuordnen und kannst dann, wenn nötig alternative Sender zuweisen. Nur einen alternativen Sender zu haben, funktioniert richtigerweise nicht mehr.

Wenn du keine alternative Sender zuweisen möchtest, warum hast du dann die Option eingeschaltet?

In der Sektion "Timer" in den Einstellungen gibt es die Option "Bouquet auswählen" die kann man aktivieren, wenn man alternative Sender nutzen möchte. Dann kann man jeweils ein Bouquet auswählen. Wenn man dann die Sender zuordnet, bekommst du, wenn du mit OK einen Sender zuordnest, zuerst die Liste aus dem ausgewählten primären (Standard) Bouquet, wenn du dort einen Sender auswählst, dann wird er in die mittlere Spalte eingefügt, wenn du dann wieder OK drückst, wird die Liste der alternativen Bouquets geöffnet und wenn du dort einen Sender wählst, wird der in die rechte Spalte einsortiert.

Wenn du generell keine alternativen Sender verwenden möchtest, dann schalte die Option in den Einstellungen ab, dann kriegst du nur eine Liste und die Zuordnung erfolgt immer in die mittlere Spalte.

Ich empfehle dringend einen Blick ins Handbuch zu werfen.

**Comment by Burny4600** [comment]
Manchmal steht man wirklich auf der Leitung.

Diesmal hatte ich die Leitung wohl nicht bemerkt worauf ich stand.

Sorry. Mein Fehler.

 

Von: MacDisein [mailto:notifications@github.com] 
Gesendet: Samstag, 14. Jänner 2017 19:16
An: einfall/serienrecorder
Cc: Burny4600; Author
Betreff: Re: [einfall/serienrecorder] STB Sender nicht gefunden. Nach wie vor Absturz bei Sender Aktualisierung. (#65)

 

Es hat mit alten Version falsch funktioniert - seit der Version 3.3.0 funktioniert es richtig, deswegen musst du jetzt die Sender als primäre Sender zuordnen und kannst dann, wenn nötig alternative Sender zuweisen. Nur einen alternativen Sender zu haben, funktioniert richtigerweise nicht mehr.

Wenn du keine alternative Sender zuweisen möchtest, warum hast du dann die Option eingeschaltet?

In der Sektion "Timer" in den Einstellungen gibt es die Option "Bouquet auswählen" die kann man aktivieren, wenn man alternative Sender nutzen möchte. Dann kann man jeweils ein Bouquet auswählen. Wenn man dann die Sender zuordnet, bekommst du, wenn du mit OK einen Sender zuordnest, zuerst die Liste aus dem ausgewählten primären (Standard) Bouquet, wenn du dort einen Sender auswählst, dann wird er in die mittlere Spalte eingefügt, wenn du dann wieder OK drückst, wird die Liste der alternativen Bouquets geöffnet und wenn du dort einen Sender wählst, wird der in die rechte Spalte einsortiert.

Wenn du generell keine alternativen Sender verwenden möchtest, dann schalte die Option in den Einstellungen ab, dann kriegst du nur eine Liste und die Zuordnung erfolgt immer in die mittlere Spalte.

Ich empfehle dringend einen Blick ins Handbuch zu werfen.
