### ISSUE TITLE
Farben in default skins

### ISSUE THREAD

**Issue by gordon55** [einfall/serienrecorder#66]
Hallo ihr Lieben,
im VTI-Forum gabs ein paar "issues" bezüglich der Skins. Daher hab ich mir die default skins im SR mal genauer angesehen, sowohl die SR_Skin.xml als auch die screens für About/Splash/Update/Startup in den py-files.
Klar isses immer schwierig, als Pluginentwickler die Skins zu definieren, die dann auch noch auf allen E2-Boxen in allen Images mit allen Skins laufen sollen.
Problemtisch ist hier meiner Meinung nach z.B. 

- in der SR_Skin.xml die Zeile mit dem "separator", in der die Farbe "grey" verwendet wird ... es soll ja Skins geben, die haben dieses "grey" nicht definiert , besser oder universeller wäre hier "#808080"

- in anderen screens wird die Farbe "white" genutzt, ok, auch die sollte eigentlich in jedem Skin definiert sein ... oder einfacher eben "#FFFFFF" nutzen ?

- wenn nur entweder "foregroundColor" oder nur "backgroundColor" bei einem widget/Text definiert ist, kommt es auf den Skin an, wie der andere Wert definiert ist. Die meisten Skins haben dunklen Hintergrund, es gibt aber auch welche mit hellem Hintergrund, da kommt dann evtl. der "weiße Adler auf weißem Grund" nicht so gut. Besser wäre es mMn. für einen default Skin, immer BEIDES zu definieren, also "foregroundColor" UND "backgroundColor" , und auch als "#rrggbb", bzw. mit Transparenz eben "#ttrrggbb".

Ich hoffe, ich hab mich verständlich ausgedrückt, bei Fragen bitte kurze PN im VTI-Forum, denn hier im GIT bin ich nicht so oft angemeldet.
Besten Dank, auch für Eurer beständiges Engagement .

**Comment by MacDisein** [comment]
Ach da ist "grey" noch drin - ändere ich.
