### ISSUE TITLE
Parsing Planer-Mail

### ISSUE THREAD

**Issue by vfbler** [einfall/serienrecorder#67]
Bei manchen Serien ist in meiner Planer-Mail eine gelbe Box mit Text hinter dem Seriennamen (z.B. bei Navy CIS: L.A. oder Der Kriminalist). Bei diesen Serien wird die Folge mit S00E00 angelegt und der Text der Box steht als Titel drin.

**Comment by vfbler** [comment]
Beispiel bei NCIS

> \<span style="font-size:10px;padding:1px;margin-left:4px;background-color:#ffff7e;border:1px solid #afccfa;" title="Fundstelle aus der Suchliste">ncis\</span>\<div style="margin-top:2px;font-weight:bold;">

**Comment by egn1** [comment]
Problem sollte mit aktuellster Version behoben sein.
