### ISSUE TITLE
Fehler Mail-Parsing

### ISSUE THREAD

**Issue by vfbler** [einfall/serienrecorder#68]
Hallo,

bei manchen Serien steht seit kurzem etwas vor der Folgennummer.

Beispiel:
NE102Mysteriöse Monolithen

> \<span style="padding:1px;margin:0 0 1px 1px;background-color:#de0000;color:#ffffff;">NE\</span>\<span style="padding:1px;margin:0 0 1px 1px;background-color:#053357;color:#ffffff;" title="Staffel">1\</span>\<span style="padding:1px;margin:0 0 1px 1px;background-color:#55cd0c;" title="Episode">02\</span>

Die Serie wird dann mit dem Namen "NE" (S00E00) aufgenommen.

**Comment by egn1** [comment]
Bitte neue Version testen.

**Comment by vfbler** [comment]
Sieht gut aus.
