### ISSUE TITLE
Einige Sendungen werden ignoriert, da alle Folgen mit S00E00 angegeben sind

### ISSUE THREAD

**Issue by mationic** [einfall/serienrecorder#69]
Seit dem Update werden einige meiner Sendungen leider nicht mehr aufgenommen. In den Logfiles hab ich gesehen, dass bei diesen Sendungen alle Folgen nur S00E00 mit angegeben werden. Der Serienrecorder geht von Duplikaten aus und ignoriert sie. Beispiele sind Presseclub und Auslandsjournal.
Wäre schön wenn man für die Folge S00E00 in den Einstellungen die Duplikat-Regel abstellen könnte.

**Comment by netwolf1** [comment]
Würde ich auch sehr begrüßen :)
Bisher umgehe ich das Problem, indem ich für solche Serien die Anzahl der Wiederholungen raufsetze, aber eine Einstellung für diese S00E00-Serien wäre natürlich eleganter.
