### ISSUE TITLE
Fehler beim Abrufen und Verabeiten der Ausstrahlungstermine

### ISSUE THREAD

**Issue by Stefan136** [einfall/serienrecorder#70]
Beim Abrufen der Sendertermine (mit Info-Taste) bekomme ich mit der Version 3.4.8-beta die Fehlermeldung.

Fehler beim Abrufen und Verabeiten der Ausstrahlungstermine

Ist das ein Problem mit dem SR oder der Webseite?

Danke :-)

**Comment by betonme** [comment]
War ein Verarbeitungsfehler im SerienServer. Ist behoben.
