### ISSUE TITLE
Staffeleinschränkungen werden nicht korrekt geladen

### ISSUE THREAD

**Issue by vfbler** [einfall/serienrecorder#72]
Nach Neustart der Box werden nicht alle Staffeleinschränkungen im SerienMarker geladen. Die Oberfläche zeigt "Ab Staffel 0" und es werden dann alle Staffeln der Serie aufgenommen. Öffnet man allerdings den Einstellungsdialog für die Einschränkung, sind die korrekten Werte gesetzt und werden danach auch an der Oberfläche wieder angezeigt bzw. berücksichtigt.

**Comment by MacDisein** [comment]
Kannst du mir bitte mal deine SerienRecorder.db schicken - dann kann ich das leichter nachvollziehen.
