### ISSUE TITLE
Buttons werden nicht alle angezeigt

### ISSUE THREAD

**Issue by schomi** [einfall/serienrecorder#74]
Im Screen serienRecSendeTermine, def setSkinProperties ist noch die alte Routine zur Anzeige der Buttons drin. Daher werden nicht alle Buttons angezeigt, obwohl so eingestellt.

**Comment by MacDisein** [comment]
Behoben in dieser Version: https://github.com/einfall/serienrecorder/commit/ef82deb74fcdf2c3518eebf5509018d4e2354af5
