### ISSUE TITLE
TV-Planer auswertung bricht ab wegen Werbung in der email

### ISSUE THREAD

**Issue by ToffiCap** [einfall/serienrecorder#75]
Hallo,
seit dem 21.11.18 befindet sich in der TV-Planer email eine Werbeanzeige an der zweiten Stelle der aufgelisteten Serien.
Die Auswertung der email wird an dieser Stelle mit der Meldung "TV-Planer: HTML Parsing mit Fehler beendet" abgebrochen.

**Comment by MacDisein** [comment]
Dafür gibt es seit gestern einen Fix - einfach die aktuellen Sourcen herunterladen und einspielen.

**Comment by ToffiCap** [comment]
Super, vielen Dank :D
