### ISSUE TITLE
SR 3.8.0 Meldung -Ungültige URL- bei TV-Planer auswertung

### ISSUE THREAD

**Issue by ToffiCap** [einfall/serienrecorder#76]
Hallo,
beim auswerten der TV-Planer Email wird ein Eintrag zum Film mit folgender Meldung geloggt:

>' Edward mit den Scherenhänden - Ungültige URL 'https://www.wunschliste.de/tv/GDM143944042' '

Hier das komplette Log:

>---------' Starte Check um 30.11.2018 - 08:41:07 (TV-Planer manuell) '-------------------------------------------------------------------------------
>
>STB Type: duo2
>Image: 14.0.0 / Release 14.0.0  (BUILD: 2015-11-17)
>SR Version: 3.8.0
>Datenbank Version: 3.8
>Skin Auflösung: 1280 x 720
>
>DEBUG Filter: Senderliste Episoden Added Disk Tageszeit Zeitlimit Timer Debug 
>
>Prüfe konfigurierte Aufnahmeverzeichnisse:
>   /media/hdd/movie/Serien/
>
>Anzahl aktiver Websender: 39
>Berücksichtige Ausstrahlungstermine zwischen 30.11.2018 - 08:41 und 14.12.2018 - 08:41
>Berücksichtige Wiederholungen zwischen 30.11.2018 - 08:41 und 14.12.2018 - 08:41
>
>---------' Lade TV-Planer E-Mail '---------------------------------------------------------------
>
>Ab dem 01.12.2018 00:00 Uhr wurden die folgenden Sendungen gefunden:
>
>' Edward mit den Scherenhänden - Ungültige URL 'https://www.wunschliste.de/tv/GDM143944042' '
>
>---------' Verarbeite TV-Planer E-Mail '-----------------------------------------------------------
>
>Abrufen von ' Agatha Christies Poirot ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Akte X ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Columbo ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Der Bulle von Tölz ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Diagnose: Mord ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Ein Käfig voller Helden ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Kampfstern Galactica ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' M*A*S*H ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Major Crimes ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Mord ist ihr Hobby ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Quincy ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' SeaQuest DSV ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Star Trek - Deep Space Nine ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Star Trek - Enterprise ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Stargate ' auch nach mehreren Versuchen nicht möglich!
>Abrufen von ' Stargate: Atlantis ' auch nach mehreren Versuchen nicht möglich!
>
>Verbleibende Zeit bis zum nächsten Auto-Check: 20:24 Stunden
>Verbleibende Zeit bis zum nächsten vollen Auto-Check: 5 Tage>
>

Gruß ToffiCap

**Comment by MacDisein** [comment]
Kannst du mir bitte mal die TV-Planer E-Mail als .eml Datei bzw. html zur Verfügung stellen.

**Comment by ToffiCap** [comment]
Kein Problem, habe beide Formate beigefügt.

[TV Wunschliste TV-Planer für Samstag, den 01.12.2018.zip](https://github.com/einfall/serienrecorder/files/2633400/TV.Wunschliste.TV-Planer.fur.Samstag.den.01.12.2018.zip)

Vielen Dank, Gruß ToffiCap

**Comment by ToffiCap** [comment]
Kein Problem

[TV Wunschliste TV-Planer für Samstag, den 01.12.2018.html.zip](https://github.com/einfall/serienrecorder/files/2633464/TV.Wunschliste.TV-Planer.fur.Samstag.den.01.12.2018.html.zip)

Vielen Dank, Gruß ToffiCap

**Comment by MacDisein** [comment]
Woher kommt denn dieser Block mit den Film (da steht etwas von "Fundstelle aus der Suchliste vincent price". Dieser Bereich ist ja außerhalb vom "Mein Serienfeed"?
Was ist denn bei "Mein Wunschliste" bei dir eingestellt?

**Comment by ToffiCap** [comment]
Vincent Price steht bei den Wunschlisten in der Suchliste. Da erscheinen dann alle Filme mit Vincent Price in der TV-Planer Mail.

![screenshot_2018-11-30 tofficaps wunschliste](https://user-images.githubusercontent.com/45296829/49300276-194b5400-f4c2-11e8-90cd-c338e117dc73.png)

**Comment by MacDisein** [comment]
Hmmm, das hat vermutlich noch kein anderer gemacht - das muss ich mir genauer ansehen - ich melde mich.

**Comment by ToffiCap** [comment]
Ok :)

**Comment by MacDisein** [comment]
So, ich habe mir das jetzt mal angesehen und meiner Meinung nach, ist das ein Fehler von Wunschliste. Die haben dort den falschen Link eingesetzt. Bisher sind mir nur die beiden URL mit "serie" bzw. "spielfilm" und der "Fernsehserie-ID" bekannt. Die URL mit "tv" verweist direkt auf den Beschreibungstext. Damit kann der SerienRecorder und auch der SerienServer nichts anfangen.

Du solltest das mal beobachten, es ist natürlich nicht auszuschließen, dass WL da etwas umgestellt hat, dann hätten wir ein Problem, aber ich hoffe mal nicht.

**Comment by ToffiCap** [comment]
Ok, ich behalts mal im Auge.

Vielen Dank, Gruß ToffiCap
