### ISSUE TITLE
Nachlaufzeiten editieren

### ISSUE THREAD

**Issue by Meden2** [einfall/serienrecorder#77]
Man kann zwar die Vor- und Nachlaufzeiten im Serienrecorder ändern, aber es hat keinerlei Auswirkungen auf die erstellten Timer. Selbst ein Löschen der Serie und neu Anlegen führt wieder zu den alten Zeit....

**Comment by Meden2** [comment]
Nein, ich erhalte keine Fehlermeldungen.....wedwer wenn ich auf globale Werte zurückstell noch wenn ich die individuellen Werte änder tut sich nichts....
Das ist neu und war früher nicht so....aber man ändert ja auch nicht so oft...hatte die Vermutung eines Bugs in der neuen Version.

Wenn bei dir alles funktioniert kann es eigentlich nur daran liegen, dass eine Datei zerschossen ist....
wenn ich nei Installiere nützt es nichts, außerdem ist danach die alte List wieder aktiv, es wir bei der deinstallation also nichts gelöscht.....das ist mir bei anderen Plugins auch schon aufgefallen.....

Wenn sich hi9er keine Hilfe ergibt muß ich wohl alles mal per Hand löschen.....
klingt nicht lustig.....alles wieder neu eingeben....

**Comment by Meden2** [comment]
Ich habe gerade nochmal ins Logfile reingesehen, da gibt es die Meldung "Sendung konnte nicht im EPG gefunden werden" werden unter aktualisieren, aber ich habe schon seit geraumer Zeit Änderungen aufgegeben, hat also eigentlich nichts mit Vor- und Nachlaufzeitänderungen zu tun....
Die Timer werden aber angelegt, wenn auch nicht mit den richtigen EPG-Zeiten...

**Comment by MacDisein** [comment]
Wie ich dir schon im VU+ Support Forum geschrieben hatte, kann ich nicht hellsehen, solange du mir weder ein Log noch deine Einstellungen zur Verfügung stellst, wird dir vermutlich niemand helfen können.

Man kann einmal eine globale Vor- und Nachlaufzeit einstellen und dann noch eine individuelle pro Marker. Um welche geht es - was hast du wo eingestellt und was wird im Log ausgegeben?

**Comment by Meden2** [comment]
Das Log hilft dir nichts.....es tut sich nichts, weder wenn dich die globalen noch die individuellen Zeit ändere. Im Log steht nur, wenn ich eine bestehenden Timer in den Vor-und Nachlaufzeiten andere, dass er schon besteht....und die neuen Timer werden mit Zeiten erzeugt, die früher mal relevant waren, jetzt aber nirgendwo für mich sichbar vorhanden sind.
Schliesse einfach mal einen Bedienungsfehler aus....so komplex ist das mit den Definitionen nun nicht.....
Ich habe es gerade einmal mit einer Serie versucht, die ich bisher nie im Serienrecorder eingefügt hatte.
Zuerst mit den globalen werten....klappt....
Dann geänderte individuelle Werte....klappt....
Dann die individuellen Werte nochmal geändert....klappt

Da ich die Timer manuell angelegt habe, hat er natürlich jedesmal einen neuen Timer erzeugt und dieses im Logfile vermerkt...Die alten Einträge sind unverändert in der Timerliste verblieben...
Das Problem bezieht sich offenbar lediglich auf bisherige Einträge......

Naja...zum testen habe ich die Anzahl der Timertage auf 2 reduziert, normalerweise nehme ich 4, da manchmal die Verbindung zum Server klemmt.....das probiere ich jetzt mit ner alten Serie....

Falls das nicht klappt.....
werde ich wohl oder übel den Serienrecorden deinstallieren und von Hand die Datenbank löschen müssen....danach Neuinstallation....

**Comment by MacDisein** [comment]
Habe ich das jetzt richtig verstanden, dass bei einem manuell angelegten Timer über den SerienRecorder die Vor- und Nachlaufzeiten korrekt berücksichtigt werden!?
Dann musst du vielleicht das Problem noch mal etwas deutlicher formulieren, wo aus deiner Sicht etwas nicht korrekt funktioniert.

**Comment by MacDisein** [comment]
Ich habe keine Ahnung was du dir von deinem sog. "Bugreport" hier und im VU+ Forum erwartet hast. Eigentlich finde ich dein überhebliche Art unangemessen. Mir zu unterstellen, dass ich einen Bedienungsfehler deinerseits annehmen würde, ist genauso unpassend und falsch wie deine Unterstellung, dass mir ein Log nicht helfen würde.
Inzwischen ist mir auch ein wenig das Interesse vergangen einen Fehler in meinem Programmcode zu suchen, weil von dir, neben deinem unangemessen Tonfall, keinerlei brauchbare Informationen kommen.

Ich weiß immer noch nicht, wie ich dein Problem nachstellen kann, oder was du wo eingestellt hast und auch nicht was der SerienRecorder an Meldungen ins Log schreibt.

Folgende Vorgehensweise hat zu dem in meinem ersten Posting beschriebenen Verhalten geführt, dass auch so im Log des SerienRecorders dokumentiert wurde.

1. Die Einstellungen des Serien-Markers (in meinem Beispiel war es GZSZ) geöffnet und dort die Vorlaufzeit von 4 auf 3 Minuten geändert. Die Nachlaufzeit auf 0 eingestellt.
2. Einstellungsdialog verlassen und Auto-Check durchgeführt

Ergebnis: Im Log wird im Bereich "Aktualisierungen" ausgegeben, dass der Startzeit des Timers geändert wurde. Ich muss jetzt allerdings zugeben, dass ich mir den Timer danach nicht mehr angesehen habe ob die Zeit wirklich verändert wurde.

Ist dein Problem, dass die Werte die du für einen Serien-Marker konfigurierst nicht abgespeichert werden oder dass sie bei einem Auto-Check nicht korrekt berücksichtigt werden. Werden neue Timer dieser Serie mit falschen Zeiten angelegt oder werden noch nicht abgearbeitete bestehende Timer nicht geändert?

Da du ja aber offensichtlich lieber selbst das Problem beheben möchtest, die Sourcen sind ja hier im gitHub eingecheckt und die Datenbank lässt sich mit dem Tool "DB Browser for SQLite" bearbeiten.

**Comment by MacDisein** [comment]
Hat sich von deiner Seite noch etwas ergeben? Ansonsten würde ich den Issue schließen wollen.
