### ISSUE TITLE
Greenscreen automatischer Suchlauf Timer

### ISSUE THREAD

**Issue by erice67** [einfall/serienrecorder#79]
[log.zip](https://github.com/einfall/serienrecorder/files/3149076/log.zip)

**Comment by MacDisein** [comment]
Da hat das Update der Datenbank nicht geklappt, ich würde empfehlen zurück auf die 3.8.17-beta zu gehen und das Backup der Datenbank wieder einzuspielen.
Ich arbeite noch an einer Lösung. Wenn du möchtest, dann kannst du mir deine Datenbank zur Verfügung stellen (per Mail) - dann habe ich einen Testkandidaten für den Bugfix.

**Comment by PaxxiFixxi** [comment]
Hallo,
gehört zwar nicht hier her aber ich wollte mal nachfragen ob eine Version für die neue Dreambox One gepnant ist ? Von diesem Plugin hängt auch meine Kaufentscheidung ab :)

**Comment by MacDisein** [comment]
Ich habe keine Dreambox One, aber ich wüsste jetzt nicht, wieso der SerienRecorder dort nicht laufen sollte.

**Comment by PaxxiFixxi** [comment]
Dachte evtl wegen dem 64bit OS. Ausser DreamOS gibt es auch derrzeit ja keine alternativen images für die Box. 
Ich werde es einfach mal testen und berichten.

**Comment by PaxxiFixxi** [comment]
Leider läuft das Plugin auf der Dreambox One nicht. Die Box bootet in einen Greenscreen und das ganze im loop. Ein Logfile wird leider nicht geschrieben.

Wäre über jede hilfe dankbar.

**Comment by MacDisein** [comment]
Bei einem Greenscreen wird eigentlich immer ein Crashlog erstellt, ansonsten einfach mal ein Bootlog machen.

**Comment by PaxxiFixxi** [comment]
Ich habe eine Version des Serienrecoders gefunden die unter Enigma 2.6 rennt :)
Kann sie auf Wunsch gerne hochladen.

**Comment by MacDisein** [comment]
Bitte per Mail an mich und ich hätte auch gerne gewusst wo die Version her kommt.
