### ISSUE TITLE
Serienmarker - Einstellungen

### ISSUE THREAD

**Issue by viebrix** [einfall/serienrecorder#81]
Wenn ich im Serienmarker mit Menü auf die Einstellung der jeweiligen Serie gehe und dort dann Zahlenfelder ändern will - wie zB bei Timervorlauf, dann funktionieren bestimmte Zahlentasten nicht. Unter anderem geht die Taste "2" nicht, weil diese für eine Coverfunktion reserviert ist.

**Comment by MacDisein** [comment]
Der Fehler wurde bereits mit der nächsten Betaversion behoben. Die Funktion, die die Taste 2 blockiert hat, wurde auf die blaue Taste verschoben, sodass jetzt alle Zahlentasten wieder für die Eingabe genutzt werden können.

**Comment by viebrix** [comment]
Super - Danke!
