### ISSUE TITLE
[Q/RFE] Automatische Senderzuordnung SD Sender

### ISSUE THREAD

**Issue by thmo** [einfall/serienrecorder#82]
Kann man die automatische Senderzuordnung irgendwie überreden, auch nicht-HD Sender zuzuordnen, z.B. wenn man nur FTA empfangen kann? Habe es mit der Einschränkung auf ein entsprechendes Bouquet probiert, wo die FTA empfangbaren HD und SD Sender drin sind - leider werden dann nur die (wenigen) HD-Sender zugeordnet, aber kein SD Sender. Gibt es da einen Trick? Oder muss man dann in der Tat alles händisch zuordnen? Falls es im Moment nicht automatisch geht, ließe sich sowas einbauen?

**Comment by MacDisein** [comment]
Bei der automatischen Senderzuordnung werden HD Sender bevorzugt. Wenn kein passender HD Sender in den Bouquets gefunden wurde, wird versucht den SD Sender zu verwendet.
Wenn du manche Sender nur in SD nutzen kannst, wieso hast du denn nicht nutzbare HD in deinen Bouquets?

**Comment by thmo** [comment]
> Bei der automatischen Senderzuordnung werden HD Sender bevorzugt. Wenn kein passender HD Sender in den Bouquets gefunden wurde, wird versucht den SD Sender zu verwendet.

Genau das hat bei mir nicht funktioniert. Ich habe ein Bouquet, in dem die nutzbaren HD und SD Sender drin sind, und das habe ich im SR konfiguriert. Bei der automatischen Zuordnung ordnet er aber nur die Sender zu, für die er HD Sender findet, die anderen lässt er leer, obwohl da durchaus passende SD Sender im Bouquet sind.

> Wenn du manche Sender nur in SD nutzen kannst, solltest du die nicht nutzbaren HD Sender aus deinen Bouquets löschen?!

Die nicht nutzbaren HD Sender sind in dem besagten Bouquet nicht drin.

**Comment by MacDisein** [comment]
Ok, das sehe ich mir an, evtl. wird die Einschränkung der Bouquets nicht richtig berücksichtigt bei der Autozuordnung oder es gibt noch ein Problem mit dem Vergleich der Namen.

**Comment by thmo** [comment]
Ok, wurde schon hier gefixt: 58a4474b.
