### ISSUE TITLE
Support python 2 and 3

### ISSUE THREAD

**Issue by jbleyel** [einfall/serienrecorder#83]
https://docs.python.org/3.3/howto/pyporting.html
https://six.readthedocs.io/
https://haptik.ai/tech/wp-content/uploads/2019/10/Python-3-Migration-Guide-2to3.pdf
https://docs.python.org/2/library/2to3.html

**Comment by jbleyel** [comment]
First shot.
Not finished!!!
https://github.com/jbleyel/serienrecorder

**Comment by jbleyel** [comment]
Any update about python 3?

**Comment by MacDisein** [comment]
As long I have no box/image to port the SerienRecorder plugin to Python 3 there will be no progress.

**Comment by jbleyel** [comment]
Openatv 6.5 is python3.

**Comment by MacDisein** [comment]
I know, but there is no image available for my test box (Axis E4HD), the focus seems to be on 4K boxes at the moment.

**Comment by MacDisein** [comment]
Version 4.2.5 ist jetzt Python 3 kompatibel
