### ISSUE TITLE
Crash !!

### ISSUE THREAD

**Issue by paparas12** [einfall/serienrecorder#84]
version 4.2.5 (s. log)
[enigma2_crash_1615794576.log](https://github.com/einfall/serienrecorder/files/6139658/enigma2_crash_1615794576.log)

**Comment by MacDisein** [comment]
Ist in der aktuellen Betaversion schon behoben.

**Comment by paparas12** [comment]
Wo ist die beta version  unter downloas zip ?,

**Comment by MacDisein** [comment]
Genau, die Sourcen herunterladen und auf die Box kopieren.

**Comment by paparas12** [comment]
danke.. Da soll noch eine Plugin für openwebif geben, wo finde ich das und wie wird es installiert wenn es kein *.deb ist?

**Comment by MacDisein** [comment]
Ich habe hier die wichtigsten Details zum Webinterface noch mal übersichtlich aufbereitet: https://github.com/einfall/serienrecorder/blob/8aae4172692393c35dfc04cc41a7c88c2cfd5d12/README.md

Wenn der SerienRecorder nicht unter Extras auftaucht, dann ist deine Version vom OpenWebIf zu alt.

**Comment by paparas12** [comment]
eher zu neu! version 1.4.9
![Uploading Snap7.jpg…]()

**Comment by MacDisein** [comment]
Mit wem hast du denn gesprochen, die letzte mir bekannte Version ist Version 1.4.4?
Bei den Dreamboxen braucht man das OpenWebIf nicht, da reicht das Webinterface das mitgeliefert wird.

**Comment by jbleyel** [comment]
Das Openwebif hat aktuell die Version 1.4.4 und ich bin einer der Programmierer.
Das Openwebif 1.4.9a ist vermutlich eine newnigma spezialversion und somit nicht offiziell.

Hallo @paparas12 : Wer bitte ist der Programmierer den du hier meinst?

Was meinst du mit  "deutsche sprache"?

**Comment by paparas12** [comment]
Hallo.
Der Programmier ist in einen ausländische Forum er versteht keine deutsch!
@jbleyel : folgende fragen zu Openwebif 1.4.4.
1. Unterstützt es das nwenigm2 image auf der dreambox dm920 (0E 2.5) ?
2. Kann ich von "extras", auf der oscam-emu webinterface zugreifen ?
3. Kann ich von "extras" auf dem serierencoder webinterface zugreifen?
4. Kann ich von "extras" auf Terminal zugreifein?
5. Per ftp auf  /tmp was zu kopieren
Das alles kann der Openwebif 1.4.9.a (außer auf der serienrecoder webinterfacebei zuzugreifen bei mir, der programmier hat bei sein Openwebif hingekriegt)
Wenn die 1.4.4 das alles kann, dann installiere ich sie!!. 
@MacDisein  Das webinterface von der Dreambox kann 2 und 5 und ausserdem sind sch**** aus

**Comment by MacDisein** [comment]
Es gab ganz früher mal schon einmal ein API für den SerienRecorder, die wurde aber nicht weiter entwickelt und durch meine neue Version ersetzt. Deswegen steckte bis April 2020 noch Code im OpenWebIf der das Anzeigen des neuen SerienRecorder Webinterfaces verhindert hat. Diese Änderung wurde wohl von newnigma OpenWebIf Port nicht übernommen.
Nachlesen kann man das hier: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1001
Aber wenn der Programmierer des Forks das nicht umsetzen möchte, musst du wohl damit leben, dass der SerienRecorder nicht unter Extras auftaucht.

**Comment by jbleyel** [comment]
Wo ist der Source Code von der Version 1.4.9?

**Comment by jbleyel** [comment]
Ja. Die 1.4.4 kann alles was du da aufgelistet hast. Außer FTP /tmp das hat nix mit dem OWF zu tun.

**Comment by paparas12** [comment]
@jbleyel,, wo finde ich das *.deb um es auszuprobieren ?
Hier ist das *.deb file fuer den OWF 1,4,9a, 
https://www.linuxsat-support.com/thread/142315-openwebif-for-dreamos/?pageNo=1
@MacDisein  Bei den programmierer klappt es, das aber nicht bei mir.

**Comment by jbleyel** [comment]
In dem LinuxSat Forum kann ich nichts runterladen.
Zudem gibt es dort sicher nur das deb File.
Ist das wirklich der Source?

Vom offiziellen OWF gibt es nur ein IPK.
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/gh-pages/enigma2-plugin-extensions-openwebif_1.4.4-git20210314_all.ipk

**Comment by paparas12** [comment]
OE2.5-Nwenigma2 unterstützt nur *.deb files, Installation,  ich frage mich wie soll das OWF 1.4.4 kompatible zu Image sein,wenn es nur als *.ipk gibt?
 Deswegen habe auch das *.deb vor dem LinuxSat forum installiert.
Du musst dich registrieren um von da was runterzulanden!

**Comment by jbleyel** [comment]
deb und ipk ist eigentlich das gleiche nur eine andere Endung und bei deb gibt es einen hash.

Ich hab mich bei dem Forum registriert und kann nur was runterladen, wenn ich dort was bezahle.
Das mache ich definitiv nicht.

Bitte hier -> 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/new?assignees=&labels=Feature+Request&template=feature_request.md&title=

Einen neuen issue öffnen und das deb dort posten.
Das ganze hat nix mit dem serienrecorder zu tun und hat hier eigentlich nix zu suchen.

**Comment by jbleyel** [comment]
Nö.. noch besser.
Ich kann mich jetzt nicht mehr anmelden.
Mein Konto ist gelöscht worden.
Das ganze ist mir echt zu blöd.
