### ISSUE TITLE
Crash version 4.2.8-beta

### ISSUE THREAD

**Issue by paparas12** [einfall/serienrecorder#85]
siehe log
[enigma2_crash_1615832071.log](https://github.com/einfall/serienrecorder/files/6144367/enigma2_crash_1615832071.log)

**Comment by MacDisein** [comment]
Das wurde schon einmal berichtet, ich konnte das allerdings bisher nicht nachvollziehen.
Kannst du genauer sagen was du gemacht hast? Vermutlich hast du ja eine ganz jungfräuliche Installation.

**Comment by paparas12** [comment]
So genau kann ich das nicht sagen..Irgendeine ein taste gedrückt, Wenn ich mich richtig erinnere war das die "menu" taste.

**Comment by MacDisein** [comment]
Ist korrigiert!
https://github.com/einfall/serienrecorder/releases/tag/v4.3.0
