### ISSUE TITLE
Erstellen des aufnahmeverzeichnis fehlerhaft

### ISSUE THREAD

**Issue by paparas12** [einfall/serienrecorder#86]
Das Aufnahmeverzeichnis soll da auch erstellt werden, wo man sich gerade befindet und nicht in den übergeordneten verzeichnis!

**Comment by MacDisein** [comment]
Ich habe mir das eben mal angesehen und kann da kein Problem erkennen, bei mir wird oberhalb der Verzeichnisliste angezeigt welches Verzeichnis aktuell ausgewählt ist, wenn ich dann auf „blau“ (Verzeichnis anlegen) drücke wird in diesem Verzeichnis der neue Ordner angelegt.
Kannst du dein Problem bitte genauer beschreiben, wie kann ich es nachstellen?

**Comment by paparas12** [comment]
1. Wenn ich in Verzeichnis media/hdd/movie **drin bin** und drücke die blue Taste, das verzeichnis wird auf /media/hdd erstellt und nicht auf der aktuellen verzeichnis.(movie)
2.Wenn ich das Verzeichnis /media/hdd/movie **Nur auswähle** aber nicht reingehe wir das verzeichnis auf /media/hdd/movie erstellt.

Meine Meinung nach ist der 1 vorgang der korrekt (wie bei Windows)

**Comment by MacDisein** [comment]
Wie gesagt, ist entscheidet was als ausgewähltes Verzeichnis angezeigt wird. Aber ich gucke mal ob ich das noch etwas benutzerfreundlicher gestalten kann.
Beim Löschen wird nicht direkt aktualisiert, sodass man nicht direkt sieht, dass das Verzeichnis gelöscht wurde, wenn man dann noch einmal auf "Löschen" drückt kommt die Meldung - das werde ich auf jeden Fall noch verbessern.

**Comment by Marti-Win7** [comment]
Hallo
Entschuldigt, wenn ich mich "einmische", aber es steht auch so in der Anleitung unter SerienMarker-Einstellungen, das man NICHT in das Verzeichnis rein soll, sondern den Cursor nur drauf setzen soll.
Der User hat ja geschrieben "Wenn ich in Verzeichnis media/hdd/movie **drin bin**". Also NICHT in movie rein, sondern nur drauf.

**Comment by MacDisein** [comment]
Ist jetzt so wie man es erwarten würde.
https://github.com/einfall/serienrecorder/releases/tag/v4.3.0
