### ISSUE TITLE
Crash version 4.3.0

### ISSUE THREAD

**Issue by paparas12** [einfall/serienrecorder#89]
Passiert wenn in den Global menu--Timer-Suchlauf den wert von Manuell auf ein andere wert einstellen will.(Pfeil tasten rechts/links)
Das Passiert nur (?) wenn zuvor eine Manuell Suchlauf durchgeführt wurde und dann den wert ändern will. .
s. log
[enigma2_crash_1617440128.log](https://github.com/einfall/serienrecorder/files/6252273/enigma2_crash_1617440128.log)

**Comment by MacDisein** [comment]
Ist mir der Betaversion 4.3.1-beta behoben.
