### ISSUE TITLE
Serienrecoder 4.4.0 inkompatible zu webinterface 0.8.0 !

### ISSUE THREAD

**Issue by paparas12** [einfall/serienrecorder#90]
s. bild

![Snap6](https://user-images.githubusercontent.com/80169305/118466508-9824bd80-b70b-11eb-9a66-59963b4e225f.jpg)

**Comment by Conan179** [comment]
https://github.com/einfall/serienrecorder/releases/tag/v4.4.0

**Comment by MacDisein** [comment]
Es wurden Änderungen an der Schnittstelle gemacht (2.1 auf 2.2) du musst immer ein SerienRecorder Webinterface benutzen, dass mit der Schnittstellenversion des SerienRecorders kompatibel ist.
In diesem Fall musst du das Webinterface Version 0.9.0 verwenden.
