### ISSUE TITLE
Crash bei Aufnahmestart und Crash-Loop

### ISSUE THREAD

**Issue by HLM0815** [einfall/serienrecorder#91]
Hallo,
ich habe bei machen Aufnahmen das Problem, dass diese beim Aufnahmestart  zum Crash führen:

[enigma2_crash_1621620777.log](https://github.com/einfall/serienrecorder/files/6538426/enigma2_crash_1621620777.log)

und ein Neustart zu wiederholenden Crashs führt

[enigma2_crash_1621620824.log](https://github.com/einfall/serienrecorder/files/6538435/enigma2_crash_1621620824.log)

solange die Aufnahme läuft (bzw. versucht wird).

Auslösender Fehler scheint wohl: "c++ exception (Unknown column name.)" zu sein!

Was ist das Problem?

**Comment by MacDisein** [comment]
Der SerienRecorder legt nur den Timer an - für die Aufnahme ist das Image verantwortlich.
Aus dem Crashlog geht hervor, dass es ein Problem mit der MediaDatabase gibt.
Mit der MediaDatenbase gibt es in letzter Zeit öfters Probleme - im Dream Multimedia Forum gibt es dazu entsprechende Threads. Vermutlich reicht es die MediaDatabase neu aufzubauen oder ganz abzuschalten.
