### ISSUE TITLE
web UI: setting 'addSingleTimersForEvent' not possible/persistent

### ISSUE THREAD

**Issue by thmo** [einfall/serienrecorder#92]
It seems to me that, using the web UI, it is not possible to set `config.plugins.serienRec.addSingleTimersForEvent`. I can select "Einzelepisoden als 'bereits getimert' markieren", but after saving and reloading the web UI the setting is again unselected, and also the `addSingleTimersForEvent` setting is gone in the e2 config. Maybe that is somehow caused by the different spelling - with or without 's' (`addSingleTimersForEvent` vs. `addSingleTimerForEvent`)?

**Comment by MacDisein** [comment]
Fixed in version 4.5.0
