### ISSUE TITLE
Season >30

### ISSUE THREAD

**Issue by HENN0** [einfall/serienrecorder#93]
Hi,

For Simpsons it is necessary to filter seasons >30

I just want to record season 32

**Comment by MacDisein** [comment]
There is no season limit, the SerienRecorder will create timer for any season if you select „Alle“ in the season select screen.
If you need to select seasons > 30 you can define the limit in the global settings „Benutzeroberfläche“ -> „Anzahl der wählbaren Staffeln im Menü Serien-Marker“.

**Comment by HENN0** [comment]
Thanks
