### ISSUE TITLE
Falsche Zuordnung der Sendung

### ISSUE THREAD

**Issue by Buchhems** [einfall/serienrecorder#99]
Die Sendung "ARTE Re:" wird einer falschen ID zugeordnet. Es wird in SR der ID 1239556 zugeordnet. Es müsste aber 297269 sein.

**Comment by MacDisein** [comment]
Ich kann dir gerade nicht folgen, von welcher ID sprichst du?
Event-ID, Wunschliste ID, TVDB-ID oder …

**Comment by Buchhems** [comment]
Sorry, es handelt sich um die TVDB-ID.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MacDisein** [comment]
Ich habe die TVDB ID geändert, allerdings zu 333933: https://thetvdb.com/series/333933-show
